### ISSUE TITLE
云函数执行报错

### ISSUE THREAD

**Issue by MilvusSky** [Womsxd/AutoMihoyoBBS#1]
和依赖一起打包后上传云函数报错
[ERROR] {
"errorMessage": "main() takes 0 positional arguments but 2 were given",
"errorType": "TypeError"
}
Error: Unhandled function error

**Comment by Womsxd** [comment]
~~应为我根本没有做云函数的支持（~~
我开发这个项目的时候基本上都是在本地环境下进行的，没有考虑到云函数的环境，不过也好解决，我上传一个测试的版本看看？

**Comment by Womsxd** [comment]
或者说httpx这个lib根本不适合腾讯云的项目上运行，我刚才去腾讯云那个试了试，httpx这个lib直接报错无法运行？
NotImplementedError: The ALPN extension requires OpenSSL 1.0.2 or later.
是我是问题？

**Comment by MilvusSky** [comment]
试试阿里云？我是在阿里云上尝试部署的

**Comment by Womsxd** [comment]
> 试试阿里云？我是在阿里云上尝试部署的

行

**Comment by Womsxd** [comment]
"errorMessage": "The ALPN extension requires OpenSSL 1.0.2 or later.",
  相同错误，要解决的话我需要把httpx这个lib更换成为其他的lib才行（

**Comment by Womsxd** [comment]
> "errorMessage": "The ALPN extension requires OpenSSL 1.0.2 or later.",
> 相同错误，要解决的话我需要把httpx这个lib更换成为其他的lib才行（

原因的话估计就是httpx这个lib支持h2，然后Openssl最低需要1.0.2才支持h2（）

**Comment by Womsxd** [comment]
只要我把httpx更换成为requests，云函数应该就全部支持了，就是config.json需要本地先写好+执行的感觉

**Comment by Womsxd** [comment]
主要还是我自己开发的时候没考虑到云函数相关的，因为自己有学生机来执行脚本了，就没做其他考虑，脚本里面的设计基本上都是根据你已经有一台Windows/Linux的服务器来进行设计的，自然没考虑到云函数的用户

**Comment by Womsxd** [comment]
请使用cloud分支再次进行尝试

**Comment by MilvusSky** [comment]
试了下，可以跑了，需要设置超时时间不能过短，并且得在本地跑一边把config.json写好，云函数执行的时候这文件只读。。
感谢

**Comment by Womsxd** [comment]
> 试了下，可以跑了，需要设置超时时间不能过短，并且得在本地跑一边把config.json写好，云函数执行的时候这文件只读。。
> 感谢

行，主要还是之前设计的时候就没怎么考虑过云函数相关的问题，现在也不想大改了，之后把云函数的多用户支持也会补上（
话说是应为什么关系才使用本项目的gayhub上类似的or比这个更好的项目都有，这个项目实际上是我个人的自娱自乐吧

**Comment by MilvusSky** [comment]
> > 试了下，可以跑了，需要设置超时时间不能过短，并且得在本地跑一边把config.json写好，云函数执行的时候这文件只读。。
> > 感谢
> 
> 行，主要还是之前设计的时候就没怎么考虑过云函数相关的问题，现在也不想大改了，之后把云函数的多用户支持也会补上（
> 话说是应为什么关系才使用本项目的gayhub上类似的or比这个更好的项目都有，这个项目实际上是我个人的自娱自乐吧

三蹦子签到仅此一家，不想天天看见mys的三蹦子版块，全是对线内容

**Comment by Womsxd** [comment]
> > > 试了下，可以跑了，需要设置超时时间不能过短，并且得在本地跑一边把config.json写好，云函数执行的时候这文件只读。。
> > > 感谢
> > 
> > 
> > 行，主要还是之前设计的时候就没怎么考虑过云函数相关的问题，现在也不想大改了，之后把云函数的多用户支持也会补上（
> > 话说是应为什么关系才使用本项目的gayhub上类似的or比这个更好的项目都有，这个项目实际上是我个人的自娱自乐吧
> 
> 三蹦子签到仅此一家，不想天天看见mys的三蹦子版块，全是对线内容

崩三的签到还是群友催更出来的233333

**Comment by Womsxd** [comment]
云函数支持已合并进主分支+支持多用户
