### ISSUE TITLE
关于配置文件的问题

### ISSUE THREAD

**Issue by cccp173** [Womsxd/AutoMihoyoBBS#101]
大佬你好，请问为什么获取到的内容只有cookie_token没有cookie，把cookiet token填进去是错的 ，我看reanme里面还是v3版本的说明，能否请麻烦大佬更新到v5版本说明

**Comment by cccp173** [comment]
![image](https://user-images.githubusercontent.com/80560564/166484540-b4c3cbdf-be12-4178-bf76-499e9228f77a.png)
好的大佬找到问题了，你的那个复制控制台命令没有把cookie字样复制进去，怪不得我找不到

**Comment by cccp173** [comment]
大佬还有一个问题，cookie到底要复制哪一部分啊，我把cookie后面从等号开始分号结束复制进去脚本提示cookie失效，不知道是哪儿出问题了

**Comment by Womsxd** [comment]
你要使用米游币功能就bbs和user两个地方都登入，然后在user这里复制粘贴readme里面的命令，把cookie赛account.cookie里面就行了

**Comment by Womsxd** [comment]
```json
  "account": {
    "cookie": "这里塞入你获取到的cookie，啥都别动，复制出来啥样这里就塞啥样",
    "login_ticket": "",
    "stuid": "",
    "stoken": ""
  },
```

**Comment by Womsxd** [comment]
隐身/无痕模式进行登入+bbs=游戏签到
隐身/无痕模式进行登入+user=米游币
隐身/无痕模式进行登入+bbs+user=游戏+米游币

**Comment by Womsxd** [comment]
> 大佬你好，请问为什么获取到的内容只有cookie_token没有cookie，把cookiet token填进去是错的 ，我看reanme里面还是v3版本的说明，能否请麻烦大佬更新到v5版本说明

没有就重新获取，别手动填，获取到啥样就粘贴啥样，还有cookie_token是在cookie里面了，你直接粘贴cookie就完事了
