### ISSUE TITLE
config找不到以下2处参数

### ISSUE THREAD

**Issue by aria4013** [Womsxd/AutoMihoyoBBS#102]
你写的README是不是错的？
找不到以下2处参数
config.json的"mihoyobbs_Cookies":" "
bbs_Global改为false

**Comment by Womsxd** [comment]
configv5更新之后没修改readme

**Comment by Womsxd** [comment]
已更新

**Comment by aria4013** [comment]
感谢，修改后经过TX云函数部署成功运行，就是多账号log都挤在一起，没有genshinhelper美观

**Comment by Womsxd** [comment]
需要进行分割？直接暴力=============切割如何？（当然也可以选择其他的切割方式

**Comment by aria4013** [comment]
都挺好，游戏绑定账号角色名字也不明显，这些我都能自己改，不过还是请考虑让所有人都用上美观的log

**Comment by aria4013** [comment]
2022-05-03 06:00:01 INFO RESULT:
🏆 原神签到福利
☁️ ✔ 1 · ✖ 0
🌈 No.1:
    ####2022-05-03####
    🔅樱 59 天空岛
    Today's reward: 摩拉 × 5000
    Total monthly check-ins: 3 days
    Status: OK
    Traveler month 5 diary
    💠primogems: 730
    🌕mora: 1000984
    ##################

**Comment by aria4013** [comment]
这个是genshinhelper的log，惊人的美观

**Comment by Womsxd** [comment]
我自己是平常真的没怎么在意log输出，平常也都是只关注相关推送的，程序的执行log更像是debug的一个手段(
