### ISSUE TITLE
请问可以将点赞次数改成10次吗？

### ISSUE THREAD

**Issue by OOKAMISAMA** [Womsxd/AutoMihoyoBBS#103]
请问可以将点赞次数改成10次吗，顺便收一下频道升级的经验。

https://github.com/Womsxd/AutoMihoyoBBS/blob/4ba03b79ded5e83128137a5d94368b47e5035eec/mihoyobbs.py#L31-L38

**Comment by Womsxd** [comment]
这里你改了也没用，会被覆盖掉

**Comment by Womsxd** [comment]
我目前是不会把这个合并进当前的主线的

**Comment by GardeniaFlower** [comment]
range(5)这里改了之后，第94行应该怎么改啊？
因为我发现米游币想兑换游戏内物品会对讨论区等级有要求，我觉得可以把任务的执行上限在完成米游币任务的前提下，顺便改成经验获取的上限，毕竟也是服务器跑，多跑一点也无伤大雅。

**Comment by GardeniaFlower** [comment]
如果能加个跑讨论区经验的功能会更好，本质上也是原有的基础上改一下就可以了。

**Comment by Womsxd** [comment]
实际我是有写了一个脚本来支持的(之前星穹铁道的时候写的

**Comment by GardeniaFlower** [comment]
> 

请问会发布吗

**Comment by Womsxd** [comment]
> > 
> 
> 请问会发布吗

可能会单独搞一个仓库来放这玩意？
这玩意我写了模拟发帖子，模拟回帖(回复自己的帖子)，模拟点赞

**Comment by GardeniaFlower** [comment]
> 可能会单独搞一个仓库来放这玩意？ 这玩意我写了模拟发帖子，模拟回帖(回复自己的帖子)，模拟点赞

期待大佬的成品

**Comment by Womsxd** [comment]
> > 可能会单独搞一个仓库来放这玩意？ 这玩意我写了模拟发帖子，模拟回帖(回复自己的帖子)，模拟点赞
> 
> 期待大佬的成品

实际是老早就写完事了，星穹铁道社区有氵经验任务的时候我给自己写的

**Comment by Teconheci** [comment]
> range(5)这里改了之后，第94行应该怎么改啊？ 因为我发现米游币想兑换游戏内物品会对讨论区等级有要求，我觉得可以把任务的执行上限在完成米游币任务的前提下，顺便改成经验获取的上限，毕竟也是服务器跑，多跑一点也无伤大雅。

94行 改为pass
