### ISSUE TITLE
难道没有老哥遇到“WARNING Config未启用！”的问题吗

### ISSUE THREAD

**Issue by huangbxaaa** [Womsxd/AutoMihoyoBBS#104]
一步步按readme走的，不成功呀
<img width="1269" alt="截屏2022-05-06 22 49 15" src="https://user-images.githubusercontent.com/22412942/167157319-1ca37cfa-1fa2-46eb-a535-4a6120f2c66e.png">

**Comment by Seele0oO** [comment]
![Screenshot_20220507_081958](https://user-images.githubusercontent.com/48525679/167230087-44a9725f-28b2-4fab-921f-5e2578c3f9b6.png)

**Comment by huangbxaaa** [comment]
找到原因了，默认给的config.json.example里最外层的enable是false....改为true就行
<img width="524" alt="截屏2022-05-07 10 24 43" src="https://user-images.githubusercontent.com/22412942/167234260-c76898f4-8c75-41ac-b7e5-bd91acc7e3a3.png">
