### ISSUE TITLE
绝区0签到id

### ISSUE THREAD

**Issue by GardeniaFlower** [Womsxd/AutoMihoyoBBS#109]
请问绝区0的签到id是8吗？
        "checkin_multi_list": [
            3,
            1,
            2,
            4,
            5, 
            6,
            8,
        ], 
        我这样填的，但是没给我去讨论区签到呀。

**Comment by Womsxd** [comment]
是8，但是因为已经获取过米游币了所以不会进行签到了，还有讨论区点赞的话会默认选取第一个ID
