### ISSUE TITLE
签到时显示未登陆

### ISSUE THREAD

**Issue by heycmm** [Womsxd/AutoMihoyoBBS#11]
{"data":null,"message":"尚未登录","retcode":-100}

**Comment by Womsxd** [comment]
#6

**Comment by heycmm** [comment]
好像不是这个问题  是在判断签到 调用这个接口的时候返回的参数 "https://api-takumi.mihoyo.com/event/bbs_sign_reward/info?act_id={}&region={}&uid={}"，别的bbs相关的都通过了

**Comment by Womsxd** [comment]
一般来讲是Cookie没抓好的关系，现在新版本要先登入 https://user.mihoyo.com 然后再登入https://bbs.mihoyo.com/ys 才能抓到完整Cookie

**Comment by Womsxd** [comment]
> 一般来讲是Cookie没抓好的关系，现在新版本要先登入 https://user.mihoyo.com 然后再登入https://bbs.mihoyo.com/ys 才能抓到完整Cookie

参考教程，只不过多了一步，有空更新(

**Comment by heycmm** [comment]
有点神奇。。。 步骤还不能反了，对比前后获取到的cookie，发现里面缺少了cookie_token字段，
移除这个字段后，成功复现再次死在签到部分，。。

**Comment by Womsxd** [comment]
> 有点神奇。。。 步骤还不能反了，对比前后获取到的cookie，发现里面缺少了cookie_token字段，
> 移除这个字段后，成功复现再次死在签到部分，。。

主要还是bbs那边移除了一个字段，直接导致主暴毙
