### ISSUE TITLE
有没有空把币兑换给整合进来？

### ISSUE THREAD

**Issue by TingHsi** [Womsxd/AutoMihoyoBBS#113]
[azurstar / Mys_Rob_Goods](https://github.com/azurstar/Mys_Rob_Goods)
一个米游社商品兑换工具

**Comment by Womsxd** [comment]
不会，有关米游币自动抢购我之前也写过，只不过项目是私有的，在完成这个项目后我就开始整了，估计最近这段时间也不会公开，去年11月之后的话已经没怎么维护了，不过在我和其他人的测试中是100%抢购成功

**Comment by Teconheci** [comment]
> 

大佬，能发下接口不

**Comment by hujihan** [comment]
> 不会，不会，我也不会在之前也写过整款项目，在完成这个项目后自动抢夺我的私藏币，在完成这个项目后，我就不需要授权，去年 1 月后我就已经开始私藏了怎么维护了，不过在我和其他人的测试中是100%抢购成功

跪求一份/磕头

**Comment by MXZHT** [comment]
跪求一份 感谢大佬 我邮箱是1011325739@qq.com
