### ISSUE TITLE
修改时间后不跑了

### ISSUE THREAD

**Issue by GardeniaFlower** [Womsxd/AutoMihoyoBBS#116]
改了yml文件，9.30改成7.30触发，但是没生效，原来9.30也不跑了。

**Comment by Womsxd** [comment]
@Darkatse

**Comment by Darkatse** [comment]
我试了下没问题啊，有没有报错信息或者日志之类的  
正常来讲在运行完脚本之后会有下次运行时间的提示，类似
`mihoyo-bbs_1  | 2022-05-14T19:05:38 INFO Current running datetime: 2022-05-14 19:05:38`
`mihoyo-bbs_1  | 2022-05-14T19:05:38 INFO Next run datetime: 2022-05-15 07:30:48`  
或者确认下格式是否符合cron格式吧，修改完yml建议用
`docker-compse stop &&  docker-compose up -d --build`
重新建立容器，然后用`docker-compse logs -f`查看运行时间的提示是否正确

**Comment by Teconheci** [comment]
> @Darkatse

腾讯云开始收费了
