### ISSUE TITLE
萌新求解如何在openwrt的docker中跑这个项目

### ISSUE THREAD

**Issue by TaoRone** [Womsxd/AutoMihoyoBBS#117]
之前从来没接触过，因为最近腾讯云的收费，所以想迁移到自己的openwrt上，但不知道如何操作……
如何把整个文件项目制作成镜像导入啊……………………

**Comment by Womsxd** [comment]
按照docker运行方式直接用就行了，openwrt是Linux内核

**Comment by TaoRone** [comment]
> 按照docker运行方式直接用就行了，openwrt是Linux内核

现在就是不知道怎么去把这个项目拉到openwrt的docker里……显示智能将jar文件传进去……
需要我先在win开个虚拟机然后再打包这个项目成镜像jar格式么

**Comment by Womsxd** [comment]
wget https://github.com/Womsxd/AutoMihoyoBBS/archive/refs/heads/master.zip
然后unzip

**Comment by Womsxd** [comment]
如果openwrt有git的话也可以git clone下来

**Comment by TaoRone** [comment]
> 如果openwrt有git的话也可以git clone下来

大佬，这个帖子其实还没结束。。。。所以我昨儿没关闭。。。

**Comment by MoXiaoXi233** [comment]
可以参考用青龙面板，https://note.moxiify.cn/post/AutoMihoyoBBS
