### ISSUE TITLE
Failed to obtain genshin account list

### ISSUE THREAD

**Issue by wbmins** [Womsxd/AutoMihoyoBBS#118]
云函数执行报这个错，不知道是哪的原因。

正在获取米哈游账号绑定的原神账号列表...

Resetting dropped connection: api-takumi.mihoyo.com

https://api-takumi.mihoyo.com:443 "GET /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn HTTP/1.1" 200 71

获取原神账号列表失败！

**Comment by Womsxd** [comment]
米游社cookie失效，只需要抓取bbs的就行了

**Comment by wbmins** [comment]
> 米游社cookie失效，只需要抓取bbs的就行了

感谢
