### ISSUE TITLE
telegram推送消息显示Address not available……

### ISSUE THREAD

**Issue by TaoRone** [Womsxd/AutoMihoyoBBS#119]
![image](https://user-images.githubusercontent.com/22138142/169580886-1142d402-c633-4026-a457-bb90868fcdfa.png)

虽然把docker弄清楚了一点，但是推送消息又有问题了……

**Comment by Womsxd** [comment]
能给推送错误详细的信息麻？

**Comment by TaoRone** [comment]
> 能给推送错误详细的信息麻？

嗯，我试试，我看大佬在代码里好像没有输出返回详细日志，自己技术比较渣，毕业后没碰过代码，也没学过python，所以简单测试了下

测试代码如下：（push.py中）
`# telegram的推送
def telegram(status, push_message):
    print("测试推送")
    
    res = requests.post(
        url="https://{}/bot{}/sendMessage".format(cfg.get('telegram','api_url'), cfg.get('telegram','bot_token')),
        data={
            "chat_id": cfg.get('telegram', 'chat_id'),
            "text": title(status) + "\r\n" + push_message
        }
    )
    print(res)
    `

测试结果如下：（BOT 的token我之后会改，所以这里就放上了）
`automihoyobbs-master-mihoyo-bbs-1  | 2022-05-21T19:07:13 INFO 正在执行推送......

automihoyobbs-master-mihoyo-bbs-1  | 2022-05-21T19:07:34 WARNING 推送执行错误：HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5243147633:AAG87W34Zr4Kp1PyCKUvAEaheGlUtc5Z_v0/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f44788a2aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))

automihoyobbs-master-mihoyo-bbs-1  | 

automihoyobbs-master-mihoyo-bbs-1  | 测试推送

automihoyobbs-master-mihoyo-bbs-1  | 2022-05-21T19:07:34 INFO Current running datetime: 2022-05-21 19:07:34

automihoyobbs-master-mihoyo-bbs-1  | 2022-05-21T19:07:34 INFO Next run datetime: 2022-05-22 09:30:19`


这个结果……是我重试太多被屏蔽了？？？

**Comment by Womsxd** [comment]
很明显，访问tg并没有走梯子

**Comment by Womsxd** [comment]
除非你不在国内

**Comment by TaoRone** [comment]
> 很明显，访问tg并没有走梯子

啊，是这个原因啊……………………晕死
再次打扰大佬一下。。。。。请问docker desktop的要走代理（旁路由）是不是这样设置。。。怎么没效果啊
![image](https://user-images.githubusercontent.com/22138142/169674356-ff0b7c1c-a954-4ce2-a3eb-a934af68a320.png)

**Comment by Womsxd** [comment]
> > 很明显，访问tg并没有走梯子
> 
> 啊，是这个原因啊……………………晕死
> 再次打扰大佬一下。。。。。请问docker desktop的要走代理（旁路由）是不是这样设置。。。怎么没效果啊
> ![image](https://user-images.githubusercontent.com/22138142/169674356-ff0b7c1c-a954-4ce2-a3eb-a934af68a320.png)
> 

这里我到不清楚了，我自己是走cqhttp推送的

**Comment by TaoRone** [comment]
> > > 很明显，访问tg并没有走梯子
> > 
> > 
> > 啊，是这个原因啊……………………晕死
> > 再次打扰大佬一下。。。。。请问docker desktop的要走代理（旁路由）是不是这样设置。。。怎么没效果啊
> > ![image](https://user-images.githubusercontent.com/22138142/169674356-ff0b7c1c-a954-4ce2-a3eb-a934af68a320.png)
> 
> 这里我到不清楚了，我自己是走cqhttp推送的

非常感谢大佬的帮助，谢谢您，很抱歉宝贵的假期打扰您了~~~
