### ISSUE TITLE
签到不了，其他功能正常

### ISSUE THREAD

**Issue by guoluyuan** [Womsxd/AutoMihoyoBBS#12]
2021-09-20T23:12:42 WARNING 获取账号签到信息失败！
{"data":null,"message":"尚未登录","retcode":-100}

**Comment by guoluyuan** [comment]
2021-09-20T23:04:42 INFO Config加载完毕
2021-09-20T23:04:42 INFO 登录成功！
2021-09-20T23:04:42 INFO 正在保存Config！
2021-09-20T23:04:42 INFO Config保存完毕
2021-09-20T23:04:47 INFO 正在获取任务列表
2021-09-20T23:04:47 INFO 新的一天，今天可以获得90个米游币
2021-09-20T23:04:47 INFO 正在获取帖子列表......
2021-09-20T23:04:48 INFO 已获取5个帖子
2021-09-20T23:04:48 INFO 正在签到......
2021-09-20T23:04:48 INFO 原神OK
2021-09-20T23:04:55 INFO 大别野OK
2021-09-20T23:05:00 INFO 正在看帖......
2021-09-20T23:05:01 INFO 看帖：刻晴满好感度了 成功
2021-09-20T23:05:05 INFO 看帖：胡桃 成功
2021-09-20T23:05:08 INFO 看帖：琴攻略！急 成功
2021-09-20T23:05:13 INFO 正在点赞......
2021-09-20T23:05:59 INFO 正在分享......
2021-09-20T23:05:59 INFO 分享：刻晴满好感度了 成功
2021-09-20T23:06:01 INFO 正在获取任务列表
2021-09-20T23:06:02 INFO 似乎还有任务没完成，今天还能获得30
2021-09-20T23:06:02 INFO 今天已经获得60个米游币，还能获得30个米游币，目前有430个米游币
2021-09-20T23:06:08 INFO 正在进行原神签到
2021-09-20T23:06:08 INFO 正在获取米哈游账号绑定原神账号列表...
2021-09-20T23:06:08 INFO 已获取到1个原神账号信息
2021-09-20T23:06:08 INFO 正在获取签到奖励列表...
2021-09-20T23:06:08 INFO 正在为旅行者蒸気波超软进行签到...
2021-09-20T23:06:10 WARNING 获取账号签到信息失败！
{"data":null,"message":"尚未登录","retcode":-100}

**Comment by Womsxd** [comment]
可能是获取顺序的问题，你是按照[README](https://github.com/Womsxd/AutoMihoyoBBS#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%A8%8B%E5%BA%8F)里面的顺序进行获取还是？

**Comment by zxjlm** [comment]
我也存在这样的问题， 发现是请求签到的时候少了 cookie_token 字段， 补上就可以了。 不知道是不是改版了。

**Comment by guoluyuan** [comment]
早上起来又试了下，不知道那个地方缺了cookie_token




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Womsxd/AutoMihoyoBBS] 签到不了，其他功能正常 (#12)





 
我也存在这样的问题， 发现是请求签到的时候少了 cookie_token 字段， 补上就可以了。 不知道是不是改版了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Womsxd** [comment]
> 早上起来又试了下，不知道那个地方缺了cookie_token

cookie_token这个字段的bbs那边给的

**Comment by zxjlm** [comment]
> > 早上起来又试了下，不知道那个地方缺了cookie_token
> 
> cookie_token这个字段的bbs那边给的

你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值.

**Comment by Womsxd** [comment]
> > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > 
> > 
> > cookie_token这个字段的bbs那边给的
> 
> 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken)拿到cookie_token的值

这个api是用stoken获取，好像我还真可以稍微整一整

**Comment by dazo66** [comment]
> > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > 
> > 
> > cookie_token这个字段的bbs那边给的
> 
> 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).

我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误

**Comment by Womsxd** [comment]
> > > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > > 
> > > 
> > > cookie_token这个字段的bbs那边给的
> > 
> > 
> > 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).
> 
> 我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误

他发你直接点击是有问题的，因为完整的url是
https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken
他后面带中午字符了

**Comment by dazo66** [comment]
> > > > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > > > 
> > > > 
> > > > cookie_token这个字段的bbs那边给的
> > > 
> > > 
> > > 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).
> > 
> > 
> > 我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误
> 
> 他发你直接点击是有问题的，因为完整的url是
> https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken
> 他后面带其他字符了

嗯嗯 我知道我后面的删掉了 看接口名称是需要Stoken ？但是我的cookie里却没有这个，是我步骤错了吗？

**Comment by zxjlm** [comment]
> > > > > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > > > > 
> > > > > 
> > > > > cookie_token这个字段的bbs那边给的
> > > > 
> > > > 
> > > > 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).
> > > 
> > > 
> > > 我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误
> > 
> > 
> > 他发你直接点击是有问题的，因为完整的url是
> > https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken
> > 他后面带其他字符了
> 
> 嗯嗯 我知道我后面的删掉了 看接口名称是需要Stoken ？但是我的cookie里却没有这个，是我步骤错了吗？

可以在setting.py这个文件里找到各种接口, @Womsxd 兄对各个接口都标得很清楚。  stoken对应的获取接口是bbs_Cookieurl2, 具体的调用流程是在login.py里面.

不过我有一个疑惑， stuid我有看到是在 login.py - line 18 通过请求接口得到的， 但是这个值和cookie里面的login_uid是重复的， 这样做是因为存在 `login_uid != stuid`的情况吗？

**Comment by Womsxd** [comment]
> > > > > > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > > > > > 
> > > > > > 
> > > > > > cookie_token这个字段的bbs那边给的
> > > > > 
> > > > > 
> > > > > 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).
> > > > 
> > > > 
> > > > 我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误
> > > 
> > > 
> > > 他发你直接点击是有问题的，因为完整的url是
> > > https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken
> > > 他后面带其他字符了
> > 
> > 
> > 嗯嗯 我知道我后面的删掉了 看接口名称是需要Stoken ？但是我的cookie里却没有这个，是我步骤错了吗？
> 
> 可以在setting.py这个文件里找到各种接口, @Womsxd 兄对各个接口都标得很清楚。 stoken对应的获取接口是bbs_Cookieurl2, 具体的调用流程是在login.py里面.
> 
> 不过我有一个疑惑， stuid我有看到是在 login.py - line 18 通过请求接口得到的， 但是这个值和cookie里面的login_uid是重复的， 这样做是因为存在 `login_uid != stuid`的情况吗？

我目前挂了14个号，刚才随便找了几个号看了下
`login_uid == `stuid`，同时`account_id`和`ltuid`也和`login_uid`一样，我到时候改下代码吧，获取这边可以稍微精简一下的感觉

**Comment by davidelectricfree** [comment]
> 
> 
> > > > > > > > 早上起来又试了下，不知道那个地方缺了cookie_token
> > > > > > > 
> > > > > > > 
> > > > > > > cookie_token这个字段的bbs那边给的
> > > > > > 
> > > > > > 
> > > > > > 你这么一说我才发现原来还要走BBS页面过一下😂, 昨天调试的时候发现也可以直接从[https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken拿到cookie_token的值](https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken%E6%8B%BF%E5%88%B0cookie_token%E7%9A%84%E5%80%BC).
> > > > > 
> > > > > 
> > > > > 我也遇到这个问题了，请问这个页面是不是要什么参数，我直接复制进去提示错误
> > > > 
> > > > 
> > > > 他发你直接点击是有问题的，因为完整的url是
> > > > https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken
> > > > 他后面带其他字符了
> > > 
> > > 
> > > 嗯嗯 我知道我后面的删掉了 看接口名称是需要Stoken ？但是我的cookie里却没有这个，是我步骤错了吗？
> > 
> > 
> > 可以在setting.py这个文件里找到各种接口, @Womsxd 兄对各个接口都标得很清楚。 stoken对应的获取接口是bbs_Cookieurl2, 具体的调用流程是在login.py里面.
> > 不过我有一个疑惑， stuid我有看到是在 login.py - line 18 通过请求接口得到的， 但是这个值和cookie里面的login_uid是重复的， 这样做是因为存在 `login_uid != stuid`的情况吗？
> 
> 我目前挂了14个号，刚才随便找了几个号看了下
> `login_uid == stuid`，同时`account_id`和`ltuid`也和`login_uid`一样，我到时候改下代码吧，获取这边可以稍微精简一下的感觉

按照readme的步骤来，似乎缺少login_ticket

**Comment by zxjlm** [comment]
login_ticket 在 [获取米游社Cookie](https://github.com/Womsxd/AutoMihoyoBBS#%E8%8E%B7%E5%8F%96%E7%B1%B3%E6%B8%B8%E7%A4%BEcookie)的第三步登陆成功后取得, 如果是Chrome, 可以下载 __EditThisCookie__ 这个插件看到.

**Comment by cxs-fight** [comment]
我测试了下 先登http://user.mihoyo.com/  再单点进http://bbs.mihoyo.com/ys/  能拿到login_ticket  但缺少cookie_token   如果直接登录http://bbs.mihoyo.com/ys/  是有cookie_token 但没有login_ticket

**Comment by davidelectricfree** [comment]
> 我测试了下 先登http://user.mihoyo.com/  再单点进http://bbs.mihoyo.com/ys/  能拿到login_ticket  但缺少cookie_token   如果直接登录http://bbs.mihoyo.com/ys/  是有cookie_token 但没有login_ticket

是我经验主义了，我是直接登录的后面的。。。

**Comment by Womsxd** [comment]
> 我测试了下 先登http://user.mihoyo.com/ 再单点进http://bbs.mihoyo.com/ys/ 能拿到login_ticket 但缺少cookie_token 如果直接登录http://bbs.mihoyo.com/ys/ 是有cookie_token 但没有login_ticket

那就试试先bbs再user

**Comment by nuthx** [comment]
3,4步换一下，先bbs再user可行！

**Comment by Womsxd** [comment]
> 3,4步换一下，先bbs再user可行！

已更正

**Comment by Womsxd** [comment]
readme顺序已经修改，请更具修改后的顺序获取

**Comment by 0x369** [comment]
stoken 怎么获取

**Comment by Womsxd** [comment]
> stoken 怎么获取

抓包user.mihoyo.com
