### ISSUE TITLE
腾讯云创不出来

### ISSUE THREAD

**Issue by qianfant** [Womsxd/AutoMihoyoBBS#120]
函数创建中...

函数创建失败, 失败原因：

未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by Womsxd** [comment]
？有没有可能是你文件上传的时候有问题？

**Comment by qianfant** [comment]
我直接选中文件夹全部上传的。

**Comment by Womsxd** [comment]
目录选择的问题吧，不应该是在有代码的目录进行上传的么？

**Comment by qianfant** [comment]
ok 了  谢谢
