### ISSUE TITLE
阿里云测试函数失败

### ISSUE THREAD

**Issue by HiiroYunia** [Womsxd/AutoMihoyoBBS#121]
“执行失败！错误类型：UnhandledInvocationError”
返回结果
{
    "errorMessage": "Handler 'main_handler_mulit' is missing on module 'index'",
    "errorType": "FunctionUnhandledError: HandlerNotFound",
    "stackTrace": [
        "HandlerNotFound: Handler 'main_handler_mulit' is missing on module 'index'"
    ]
}
我大小号两个json文件，不论是python main_multi.py执行一次→创建函数，还是python main_multi.py autorun执行一次→创建函数，测试函数均执行失败（请求处理程序都是index.main_handler_mulit）。完全跟着流程走（也有可能我小白到理解不了流程的地步），哪位大佬能解答一下吗..

**Comment by Womsxd** [comment]
这出现问题了啊，异步不用勾选的

**Comment by HiiroYunia** [comment]
> 这出现问题了啊，异步不用勾选的
那从上面的返回结果能知道原因吗？不能的话我再试试

**Comment by HiiroYunia** [comment]
> 这出现问题了啊，异步不用勾选的

那从上面的返回结果能知道原因吗？不能的话我再试试
