### ISSUE TITLE
请问如何保证cookie不过期？

### ISSUE THREAD

**Issue by kunagisatomo** [Womsxd/AutoMihoyoBBS#122]
昨天成功跑了一遍代码，今天就提示cookie已经失效，我是按照说明用无痕模式登陆的三个账号，复制完cookie直接关闭的窗口，这种情况cookie能长时间保存吗？还是我操作哪里有问题？

**Comment by xwfer** [comment]
我也是这个问题，阿里云函数配了cookie测试正常运行，第二天定时执行cookie就失效了，你是什么原因啊？
