### ISSUE TITLE
【建议】希望可以添加签到时握手超时判定，进行重试或push通知

### ISSUE THREAD

**Issue by sahuidhsu** [Womsxd/AutoMihoyoBBS#124]
首先感谢代码，确实运行效率很高很方便
我一直是将脚本放在一台位于欧洲的树莓派上运行的，之前都没有什么问题，今天不知道是不是米哈游的CDN崩了，试了好几次都出现了握手连接超时的情况（试了很多次都会随机在其中一个config运行时超时，不是某个账号的问题）
具体症状是在获取完原神角色，显示正在进行签到后程序崩溃，报错信息：`httpx.ConnectTimeout: _ssl.c:1106: The handshake operation timed out`
我把脚本换到香港服务器后运行正常了:D 但如果可以的话建议添加个判定防崩溃

**Comment by Womsxd** [comment]
在request里面有设置了httpx和requests的重试可能要增加httpx的超时时长了，现在是10s

**Comment by sahuidhsu** [comment]
> 在request里面有设置了httpx和requests的重试可能要增加httpx的超时时长了，现在是10s

那奇怪了，为啥会超时崩溃呢 不会报错？是不是握手时超时和连接超时不一样啊

**Comment by Womsxd** [comment]
> > 在request里面有设置了httpx和requests的重试可能要增加httpx的超时时长了，现在是10s
> 
> 那奇怪了，为啥会超时崩溃呢 不会报错？是不是握手时超时和连接超时不一样啊

估计还要加时间，加到15看看，或者是cdn炸了(
