### ISSUE TITLE
如果改成放在actions里workflow执行有没有被封的风险

### ISSUE THREAD

**Issue by cxs-fight** [Womsxd/AutoMihoyoBBS#13]

**Comment by Womsxd** [comment]
你确定？这个是直接读文件的，不是读环境变量的

**Comment by Womsxd** [comment]
你敢用actions公开你的config我是真的佩服你(

**Comment by cxs-fight** [comment]
我的意思是 如果改成用cookie信息从环境变量中读 然后放在action里跑 会不会被封了😂

**Comment by Womsxd** [comment]
> 我的意思是 如果改成用cookie信息从环境变量中读 然后放在action里跑 会不会被封了😂

目前我没试过，不过感觉会被github当滥用处理掉吧

**Comment by Womsxd** [comment]
目前github对action的滥用检测感觉蛮严格的

**Comment by Womsxd** [comment]
这玩意我建议tx/ali的云函数跑吧

**Comment by cxs-fight** [comment]
ok
