### ISSUE TITLE
推送报错

### ISSUE THREAD

**Issue by Fahaxikiii** [Womsxd/AutoMihoyoBBS#131]
大佬你好，我用Python执行时可以正常推送但是docker运行不能正常推送是为什么？![image](https://user-images.githubusercontent.com/93320886/173254939-92f714ab-d11c-4d31-bb3a-d3a574e91f34.png)

**Comment by Womsxd** [comment]
https://jaminzhang.github.io/python/analysis-the-errno-111-connection-refused-in-pyhton/
推送服务器的问题还是？我现在也有点搞不懂
