### ISSUE TITLE
阿里云函数部署测试函数报错

### ISSUE THREAD

**Issue by zs1211** [Womsxd/AutoMihoyoBBS#134]
本地可以正常运行，部署到阿里云函数报错这个 

{
    "errorMessage": "Function not ready: failed to start container in 0.1 seconds. Error: invalid start command: index.main_handler_mulit."
}

**Comment by Womsxd** [comment]
你要修改一下执行时间，起码要给2分钟

**Comment by Womsxd** [comment]
不对不是这个问题，感觉是你`index.main_handler_mulit.`应该改成`index.main_handler_mulit`

**Comment by Womsxd** [comment]
你好像多了个点

**Comment by zs1211** [comment]
> 你好像多了有没有种可能这个点是报错信息里的   哈哈

**Comment by zs1211** [comment]
![image](https://user-images.githubusercontent.com/24407552/183555752-0a7e313c-d561-47e2-97d5-397eee90c236.png)

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/24407552/183555752-0a7e313c-d561-47e2-97d5-397eee90c236.png)

不是http函数啊，是事件函数啊

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/183556125-a48a1d4e-1eae-493a-b2ef-c1e0b233a27f.png)

**Comment by zs1211** [comment]
![image](https://user-images.githubusercontent.com/24407552/183557249-463b5871-3133-4780-ac04-3b8f967280c6.png)

**Comment by zs1211** [comment]
![image](https://user-images.githubusercontent.com/24407552/183557526-c19b4075-8437-4c84-8e2e-0f73d8ea173d.png)

**Comment by zs1211** [comment]
根据[官方文档](https://help.aliyun.com/document_detail/422183.html) 进行安装模块并打包   不过这一步没能理解要干啥 所以没做这一步，直接把本地运行成功的文件夹上传了

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/183557816-f50eb8f4-f6bd-4d92-9a6e-a65448733cb3.png)
文件找到

**Comment by zs1211** [comment]
![image](https://user-images.githubusercontent.com/24407552/183558051-96ad3637-69de-48fd-bf3f-f743cef6e17c.png)

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/183558211-73c80910-d93e-427f-acc9-06f7add2c82e.png)
你创建是一个这样子的吗？

**Comment by Womsxd** [comment]
https://fcnext.console.aliyun.com/cn-hangzhou/tasks/function-create
我现在有点奇怪，我的创建界面和你不一样

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/183558308-1d2d248f-e0b0-4ee5-9f02-ee64818de6ef.png)

**Comment by zs1211** [comment]
done
![image](https://user-images.githubusercontent.com/24407552/183558857-82f3782d-bf67-4c96-b87f-9f6b6c557ff6.png)

看起来是创建的问题，我这边点创建默认是中间这个

**Comment by zs1211** [comment]
已经成功运行了

**Comment by Womsxd** [comment]
用第一个，不要选择第二个，第二个是webserver，用不到

**Comment by zs1211** [comment]
好家伙，咋就只有我踩了这个坑
