### ISSUE TITLE
运行无法一次性拿完所有米游币

### ISSUE THREAD

**Issue by daidaidayouxia** [Womsxd/AutoMihoyoBBS#141]
INFO Config加载完毕
 INFO 正在获取任务列表
 INFO 今天已经全部完成了！一共获得110个米游币，目前有8253个米游币
 INFO 正在进行原神签到
 INFO 正在获取米哈游账号绑定原神账号列表...
 INFO 已获取到1个原神账号信息
 INFO 正在获取签到奖励列表...
 INFO 正在为旅行者么么哒米诺进行签到...
这是第三次跑完才能完全拿完米游币。第一次显示剩下50个未获取，第二次30，跑第三次才能拿满110，无报错，这种情况如何解决？

**Comment by Womsxd** [comment]
这种情况我也不怎么清楚，可能是和网络环境有关吧
