### ISSUE TITLE
新版docker不支持arm64了？运行直接报错

### ISSUE THREAD

**Issue by Ariaxi** [Womsxd/AutoMihoyoBBS#142]
mihoyo-bbs_1  | standard_init_linux.go:228: exec user process caused: exec format error
automihoyobbs_mihoyo-bbs_1 exited with code 1

另TG推送不了。

**Comment by Ariaxi** [comment]
不是代理问题，服务器在境外，奇怪了push配置没错啊

**Comment by Womsxd** [comment]
脚本的话是python编写的，不大可能不支持Arm，docker问题应该要@Darkatse
push_server=telegram 的情况下应该是正常的，你看下push的server是不是telegram

**Comment by Ariaxi** [comment]
好吧，直接报错停止，应该都没运行到推送消息

**Comment by Darkatse** [comment]
确实是可以支持arm的，只不过我目前没有arm机器，跨平台编译docker我也没试过。
不过你有原生arm可以试试编译一下，把项目里的Dockerfile第一行改成FROM arm64v8/python:3-alpine，删去USER app避免权限问题即可进行编译。编译好后手动修改docker-compose就能运行了。

**Comment by Ariaxi** [comment]
> 确实是可以支持arm的，只不过我目前没有arm机器，跨平台编译docker我也没试过。 不过你有原生arm可以试试编译一下，把项目里的Dockerfile第一行改成FROM arm64v8/python:3-alpine，删去USER app避免权限问题即可进行编译。编译好后手动修改docker-compose就能运行了。

重新编译后可以运行，感谢。

**Comment by Darkatse** [comment]
> > 确实是可以支持 arm 的，只不过我目前没有 arm 机器，跨平台编译 docker 我也没试过。 不过你有原生 arm 可以试试编译一下，把项目里的 Dockerfile 第一行改成 FROM arm64v8/python:3-alpine，删去 USER app 避免权限问题即可进行编译。编译好后手动修改 docker-compose 就能运行了。
> 
> 重新编译后可以运行，感谢。

尝试跨平台编译了一下arm架构的，现在应该可以运行了。

**Comment by Ariaxi** [comment]
> > > 确实是可以支持 arm 的，只不过我目前没有 arm 机器，跨平台编译 docker 我也没试过。 不过你有原生 arm 可以试试编译一下，把项目里的 Dockerfile 第一行改成 FROM arm64v8/python:3-alpine，删去 USER app 避免权限问题即可进行编译。编译好后手动修改 docker-compose 就能运行了。
> > 
> > 
> > 重新编译后可以运行，感谢。
> 
> 尝试跨平台编译了一下arm架构的，现在应该可以运行了。

重新拉了一次，可以运行。
