### ISSUE TITLE
使用cqhttp通知怎么配置 access-token

### ISSUE THREAD

**Issue by kumu7y** [Womsxd/AutoMihoyoBBS#144]
![QQ图片20220723121733](https://user-images.githubusercontent.com/85327198/180590129-587151b4-4157-4d35-9b22-bf80f649125e.png)
我在push.ini文件中并没有看到关于 access-token的选项啊

**Comment by Womsxd** [comment]
/send_private_msg?access_token=114514
类似这样子配置就行了

**Comment by kumu7y** [comment]
> /send_private_msg?access_token=114514
> 类似这样子配置就行了

直接在push.ini里添加吗

**Comment by Womsxd** [comment]
修改cqhttp_url，在send_private_msg后面加上?access_token=你的密钥

**Comment by Womsxd** [comment]
原本准备改代码的，但是翻了下onebot11的文档发现可以直接在url里加(

**Comment by kumu7y** [comment]
> 原本准备改代码的，但是翻了下onebot11的文档发现可以直接在url里加(

OKOK，我去试试
