### ISSUE TITLE
崩坏3的签到不行了

### ISSUE THREAD

**Issue by yaoli159** [Womsxd/AutoMihoyoBBS#149]
![IMG_20220801_004749](https://user-images.githubusercontent.com/110125579/182036834-c64800f2-7c01-4abb-ab24-328306869a82.jpg)
大佬 要怎么搞

**Comment by lansepeach** [comment]
签到补给换链接了，看看大佬怎么修复吧

**Comment by lansepeach** [comment]
有人回答了，自己改一下文件
