### ISSUE TITLE
折腾一下午，发现这崩坏3的签到接口真难抓，不是我这个小白玩的，溜了等作者大大了

### ISSUE THREAD

**Issue by lansepeach** [Womsxd/AutoMihoyoBBS#151]
折腾一下午，发现这崩坏3的签到接口真难抓，不是我这个小白玩的溜了等作者大大了

**Comment by SakuraXiaoWen** [comment]
崩三接口和崩二改的差不多了

https://webstatic.mihoyo.com/bbs/event/signin/bh3/index.html?bbs_auth_required=true&act_id=e202207181446311&bbs_presentation_style=fullscreen&utm_source=bbs&utm_medium=mys&utm_campaign=icon

https://api-takumi.mihoyo.com/event/luna/home?lang=zh-cn&act_id=e202207181446311

https://api-takumi.mihoyo.com/event/luna/extra_award?act_id=e202207181446311&lang=zh-cn

https://api-takumi.mihoyo.com/event/luna/info?lang=zh-cn&act_id=e202207181446311&region=（）&uid=（）

https://api-takumi.mihoyo.com/event/luna/sign

改一下崩二的就能用，我已经成功了
![QQ图片20220801210251](https://user-images.githubusercontent.com/46924591/182154003-e330e97d-0051-4587-979f-37d659b0f670.png)

**Comment by z1shiki** [comment]
honkai3rd.py里直接复制honkai2.py
替换honkai2成honkai3rd bh2成bh3就好
只有几个字段 自己看看就行

setting.py里崩坏3自动签到相关设置改成
```
honkai3rd_Act_id = "e202207181446311"
honkai3rd_checkin_rewards = f'{web_Api}/event/luna/home?lang=zh-cn&act_id={honkai3rd_Act_id}'
honkai3rd_Is_signurl = honkai2_Is_signurl 
honkai3rd_Sign_url = honkai2_Sign_url
```

**Comment by lansepeach** [comment]
> honkai3rd.py里直接复制honkai2.py 替换honkai2成honkai3rd bh2成bh3就好 只有几个字段 自己看看就行
> 
> setting.py里崩坏3自动签到相关设置改成
> 
> ```
> honkai3rd_Act_id = "e202207181446311"
> honkai3rd_checkin_rewards = f'{web_Api}/event/luna/home?lang=zh-cn&act_id={honkai3rd_Act_id}'
> honkai3rd_Is_signurl = honkai2_Is_signurl 
> honkai3rd_Sign_url = honkai2_Sign_url
> ```

十分感谢我只注意到了 honkai3rd_Act_id = "e202207181446311"  下面的东西就看不懂了，谢谢解答

**Comment by lansepeach** [comment]
> 崩三接口和崩二改的差不多了
> 
> https://webstatic.mihoyo.com/bbs/event/signin/bh3/index.html?bbs_auth_required=true&act_id=e202207181446311&bbs_presentation_style=fullscreen&utm_source=bbs&utm_medium=mys&utm_campaign=icon
> 
> https://api-takumi.mihoyo.com/event/luna/home?lang=zh-cn&act_id=e202207181446311
> 
> https://api-takumi.mihoyo.com/event/luna/extra_award?act_id=e202207181446311&lang=zh-cn
> 
> [https://api-takumi.mihoyo.com/event/luna/info?lang=zh-cn&act_id=e202207181446311&region=（）&uid=（）](https://api-takumi.mihoyo.com/event/luna/info?lang=zh-cn&act_id=e202207181446311&region=%EF%BC%88%EF%BC%89&uid=%EF%BC%88%EF%BC%89)
> 
> https://api-takumi.mihoyo.com/event/luna/sign
> 
> 改一下崩二的就能用，我已经成功了 ![QQ图片20220801210251](https://user-images.githubusercontent.com/46924591/182154003-e330e97d-0051-4587-979f-37d659b0f670.png)

十分感谢

**Comment by Womsxd** [comment]
全部同一个模板了么hhh，崩2代码是我复制粘贴原神的

**Comment by Womsxd** [comment]
感觉可以合并一下签到的脚本了，现在4个游戏的签到基本都是同一个逻辑了
