### ISSUE TITLE
米游社的一些接口似乎改了，返回invalidrequest

### ISSUE THREAD

**Issue by Chika99** [Womsxd/AutoMihoyoBBS#157]
如题

**Comment by Womsxd** [comment]
哪些地方出现这个问题？

**Comment by Chika99** [comment]
`https://api-takumi.mihoyo.com/apihub/sapi/upvotePost` `https://api-takumi.mihoyo.com/apihub/sapi/signIn`尝试了这几个（不止这几个）似乎有问题，获取任务状态没有问题

**Comment by Chika99** [comment]
米游币的执行部分

**Comment by Chika99** [comment]
感觉是sapi这一系列的改了，接口版本过低了？

**Comment by Womsxd** [comment]
好像大改了米游币部分的api

**Comment by Womsxd** [comment]
刚抓包看了下

**Comment by Womsxd** [comment]
似乎改动不大

**Comment by Womsxd** [comment]
> `https://api-takumi.mihoyo.com/apihub/sapi/upvotePost` `https://api-takumi.mihoyo.com/apihub/sapi/signIn`尝试了这几个（不止这几个）似乎有问题，获取任务状态没有问题

bbs是这些https://bbs-api.mihoyo.com(

**Comment by Womsxd** [comment]
ds算法过期了，需要拿新的ds算法了

**Comment by Chika99** [comment]
> > `https://api-takumi.mihoyo.com/apihub/sapi/upvotePost` `https://api-takumi.mihoyo.com/apihub/sapi/signIn`尝试了这几个（不止这几个）似乎有问题，获取任务状态没有问题
> 
> bbs是这些https://bbs-api.mihoyo.com(

哦哦，我这个估计比较老的接口了

**Comment by Womsxd** [comment]
salt拿到了，签到这边好像无法使用

**Comment by Womsxd** [comment]
社区签到炸了，看帖，点赞，分享都是正常的

**Comment by Womsxd** [comment]
@Chika99 你这边是哪些不能用，是全部失效还是社区签到？

**Comment by Chika99** [comment]
我看看，现在只需要新盐就可以吗？

**Comment by Chika99** [comment]
还是算法也需要和之前那种，后面带上请求参数的算法

**Comment by Womsxd** [comment]
> 我看看，现在只需要新盐就可以吗？

确定了，接口不需要更新，只需要更新salt就行了，等会我推送一下，逆向2.28.1拿到的

**Comment by Chika99** [comment]
ok，牛

**Comment by Womsxd** [comment]
OK了，已经推送了
