### ISSUE TITLE
WARNING Config未启用！

### ISSUE THREAD

**Issue by Accelerator688** [Womsxd/AutoMihoyoBBS#162]
![1](https://user-images.githubusercontent.com/62538915/182996086-73bc4c42-ae7f-4559-9e03-5736a9c5837a.png)

**Comment by Accelerator688** [comment]
是我sb了，把开头的enable:false改成true就可以了

**Comment by Womsxd** [comment]
要不单用户移除掉改enable？多用户倒是有必要保留这个功能

**Comment by Accelerator688** [comment]
这个我不好说，但是我觉得把它在readme里写出来好一点
