### ISSUE TITLE
我觉得仓库要不要稍微改改名字

### ISSUE THREAD

**Issue by Mark9804** [Womsxd/AutoMihoyoBBS#17]
[一周前左右开始有大量仓库被gank了](https://github.com/Arondight/Adachi-BOT/issues/57#issuecomment-926564846)，并且

> 被封的仓都引用了[条款](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies)中的第四条（中文第九条），邮件的大意是仓库模拟了用户的真实行为，这个就可以随便扩张解释了

另外一个专注原神游戏内签到功能的[genshinhelper](https://github.com/y1ndan/genshinhelper)现在也无了，所以我觉得要不要把仓库名字的Auto，和readme当中的“自动”之类的字眼给下掉

**Comment by 602035265** [comment]
那个项目貌似是因为动用action功能，有人在用网站的action功能挖矿，所以把这种大量使用action的给端了

**Comment by Mark9804** [comment]
> 那个项目貌似是因为动用action功能，有人在用网站的action功能挖矿，所以把这种大量使用action的给端了

`genshin-impact-helper`确实是因为滥用action被封禁的，helper完全移除了action功能，所以这个说法很有道理但是感觉不太能站得住脚，还是从“模拟用户的真实行为”进行解读更妥当一些

**Comment by 602035265** [comment]
soga，那也很蛋疼了，希望作者留个底能在别的地方进行项目更新，或者直接使用指令更新什么的，感觉代码还是蛮好用的

**Comment by Womsxd** [comment]
目前仓库名称我还没改，readme里面已经改成了辅助
