### ISSUE TITLE
报错怎么解决

### ISSUE THREAD

**Issue by tjzq** [Womsxd/AutoMihoyoBBS#173]
执行pip install -r requirements.txt报错
![image](https://user-images.githubusercontent.com/110594770/183257548-c11497e2-b3c5-442d-a70a-66da2239bf3a.png)

**Comment by Womsxd** [comment]
啥运行环境

**Comment by tjzq** [comment]
> 啥运行环境

linux

**Comment by tjzq** [comment]
> 啥运行环境

ubuntu

**Comment by Womsxd** [comment]
确定python3环境吗？Ubuntu应该还有默认py2的情况吧？

**Comment by tjzq** [comment]
> 确定python3环境吗？Ubuntu应该还有默认py2的情况吧？
执行python --version得到的是3.9.9版本
![image](https://user-images.githubusercontent.com/110594770/183274410-2398c47a-bd1c-44ff-b451-30777e2c829d.png)
使用python3运行也会报错
![Uploading image.png…]()
