### ISSUE TITLE
获取账号签到信息失败。。大佬能帮忙看一下吗

### ISSUE THREAD

**Issue by Ljjjj-qm** [Womsxd/AutoMihoyoBBS#18]
米游币可以拿到，就是游戏签到奖励拿不到是咋回事啊

报错信息：
获取账号签到信息失败！
{"data":null,"message":"尚未登录","retcode":-100}

**Comment by Womsxd** [comment]
#12

**Comment by Ljjjj-qm** [comment]
啥？😅
