### ISSUE TITLE
参考这个教程步骤，但是运行报错

### ISSUE THREAD

**Issue by xifeng0** [Womsxd/AutoMihoyoBBS#180]
我写了一个比较易懂的教程https://note.moxiify.cn/post/AutoMihoyoBBS

_Originally posted by @MoXiaoXi233 in https://github.com/Womsxd/AutoMihoyoBBS/issues/77#issuecomment-1156636494_

**Comment by xifeng0** [comment]
![image](https://user-images.githubusercontent.com/76558682/184506185-b912de89-ff17-4929-a389-33cb85bfc00c.png)
青龙版本为2.13.8
请问下有人知道是什么情况吗？

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/76558682/184506185-b912de89-ff17-4929-a389-33cb85bfc00c.png)
> 青龙版本为2.13.8
> 请问下有人知道是什么情况吗？

多了个换行

**Comment by xifeng0** [comment]
> > ![image](https://user-images.githubusercontent.com/76558682/184506185-b912de89-ff17-4929-a389-33cb85bfc00c.png)
> > 青龙版本为2.13.8
> > 请问下有人知道是什么情况吗？
> 
> 多了个换行

请问下大佬是哪个地方多了个换行？小白不太懂，谢谢

**Comment by Jachaganhio** [comment]
> 

你的xifeng.json配置的有问题，看一下是不是json格式不对比如多了少了括号或者换行空格之类的

**Comment by Jachaganhio** [comment]
> 


你的xifeng.json配置的有问题，看一下是不是json格式不对比如多了少了括号或者换行空格之类的
