### ISSUE TITLE
签到失败需要验证码

### ISSUE THREAD

**Issue by EBSMMF** [Womsxd/AutoMihoyoBBS#181]
2022-08-14T18:15:25 WARNING 账号签到失败！原因: 验证码
json信息:{"retcode":0,"message":"OK","data":{"code":"","risk_code":375,"gt":"f1342eaf43e356aa680d18f55fa1f1ca","challenge":"037aac44a5484f71976d842007d672ba","success":1}}

这个验证码是什么原因出现的..怎么样子才能解决..

**Comment by Canary233** [comment]
https://github.com/DGP-Studio/Snap.Genshin/issues/375

**Comment by wangzboo** [comment]
我也遇到相同的问题

**Comment by Womsxd** [comment]
合并到 #179
