### ISSUE TITLE
tearsofthemis没有这个模块鸭

### ISSUE THREAD

**Issue by UMRQWQ** [Womsxd/AutoMihoyoBBS#182]
我把你这个import 这个模块那行删掉能跑了

**Comment by MilvusSky** [comment]
源码有tearsofthemis.py，看起来是用来签未定的

**Comment by Womsxd** [comment]
> 源码有tearsofthemis.py，看起来是用来签未定的

这个就是用来签到未定的

**Comment by Womsxd** [comment]
你要不试试拉取github的最新源码看看

**Comment by UMRQWQ** [comment]
是我代码没有更新了。。。
