### ISSUE TITLE
原神签到

### ISSUE THREAD

**Issue by lll666666** [Womsxd/AutoMihoyoBBS#184]
原神签到有问题，推送说签到成功了，但我上游戏的邮箱里并没有，手机上看米游社确实没有成功签到

**Comment by Gypsophila123** [comment]
我也遇到了这个问题，日志里面连续两天显示获得一样的奖励
![image](https://user-images.githubusercontent.com/63332682/184642083-c72452d5-a65b-4c8b-a08b-40c6ad9054aa.png)
![image](https://user-images.githubusercontent.com/63332682/184642196-6a5c1020-c6a2-47cd-bab1-3fbece46937b.png)

**Comment by Gypsophila123** [comment]
似乎在另一个issue里找到了解决办法，不确定是否有效
https://github.com/Womsxd/AutoMihoyoBBS/issues/179#issuecomment-1214276643
> 个人解决方法是把setting.py 里的User-Agent 改成你自己的设备的。原来默认的是安卓 如果你常用设备是苹果 那就会触发风控（接口返回risk_code不为0） `'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) miHoYoBBS/{}'.format(mihoyobbs_Version),`

**Comment by Womsxd** [comment]
合并到 #179
