### ISSUE TITLE
pushplus推送

### ISSUE THREAD

**Issue by yaoli159** [Womsxd/AutoMihoyoBBS#188]
![IMG_20220816_211043](https://user-images.githubusercontent.com/110125579/184889192-cfd2b749-3b02-4ca9-b513-b82ff579f168.jpg)

大佬这是哪出问题了

**Comment by Womsxd** [comment]
指定推送服务器了吗？

**Comment by Womsxd** [comment]
pushserver的cqhttp改成pushplus

**Comment by Womsxd** [comment]
我这边默认是cqhttp推送，需要手动指定推送服务器

**Comment by yaoli159** [comment]
> pushserver的cqhttp改成pushplus

解决了，谢谢大佬
