### ISSUE TITLE
想修改脚本运行时间应该改哪个文件

### ISSUE THREAD

**Issue by a476990982** [Womsxd/AutoMihoyoBBS#192]
想试试把开始签到时间改到晚上避开高峰期能不能少触发验证码

**Comment by Womsxd** [comment]
docker吗？

**Comment by a476990982** [comment]
> docker吗？

对

**Comment by Elletear** [comment]
README: https://github.com/Womsxd/AutoMihoyoBBS#:~:text=%E5%A6%82%E6%9E%9C%E6%83%B3%E8%87%AA%E8%A1%8C%E4%BF%AE%E6%94%B9%E6%97%B6%E9%97%B4%E5%8F%AF%E8%87%AA%E8%A1%8C%E7%BC%96%E8%BE%91docker%2Dcompose.yml%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84CRON_SIGNIN%EF%BC%8C%E5%B0%86%E5%85%B6%E4%BF%AE%E6%94%B9%E6%88%90%E6%83%B3%E8%BF%90%E8%A1%8C%E7%9A%84%E6%97%B6%E9%97%B4%E3%80%82

**Comment by Elletear** [comment]
READEME: `每次运行Docker容器后，容器内将自动按照参数执行签到活动，签到完成后容器将默认在每天上午9:30运行一次，如果想自行修改时间可自行编辑docker-compose.yml文件中的CRON_SIGNIN，将其修改成想运行的时间。`

**Comment by heyuhua1992** [comment]
我用的是docker中装qinglong 然后设置任务的，你看看能用的上不

1. docker 中安装青龙
docker run -dit \
   -v /mnt/mmcblk2p4/mydata/docker/ql-jd:/ql/data \
   -p 48882:5700 \
   --name qinglong-jd \
   --hostname qinglong-jd \
   --restart unless-stopped \
   whyour/qinglong:develop 

48882 为端口 自己改，  
映射路径自己改 -v /mnt/mmcblk2p4/mydata/docker/ql-jd:/ql/data  
目前的develop 版本为 2.13.8
2. 然后把下载的Womsxd_AutoMihoyoBBS文件解压缩放到scripts中
路径 /mnt/mmcblk2p4/mydata/docker/ql-genshin/scripts

3. 把配置好的json文件放到config中
路径 /mnt/mmcblk2p4/mydata/docker/ql-genshin/scripts/Womsxd_AutoMihoyoBBS/config

4. 登录qinglong后 在定时任务 新建任务
名称 随意
命令 task Womsxd_AutoMihoyoBBS/main_multi.py
定时规则 10 1,4,23 * * *

上面的定时规则 是每天的 1, 4, 23时 10分的时候开始运行，就是一天运行了3次
![4](https://user-images.githubusercontent.com/33948765/185609007-6f521b00-2a43-447c-b71a-aea3488214b3.jpg)

**Comment by a476990982** [comment]
> READEME: `每次运行Docker容器后，容器内将自动按照参数执行签到活动，签到完成后容器将默认在每天上午9:30运行一次，如果想自行修改时间可自行编辑docker-compose.yml文件中的CRON_SIGNIN，将其修改成想运行的时间。`

明白了，感谢回答

**Comment by a476990982** [comment]
> 我用的是docker中装qinglong 然后设置任务的，你看看能用的上不
> 
> 1. docker 中安装青龙
> 
> ```js
> docker run -dit \
>    -v /mnt/mmcblk2p4/mydata/docker/ql-genshin:/ql/data \
>    -p 48883:5700 \
>    --name qinglong-genshin \
>    --hostname qinglong-genshin \
>    --restart unless-stopped \
>    whyour/qinglong:develop
> ```
> 
> 48883 为端口 自己改， 同时注意你的防火墙有没有打开这个端口 /mnt/mmcblk2p4/mydata/docker/ql-genshin 映射路径自己改 目前的develop 版本为 2.13.8 2. 然后把下载的Womsxd_AutoMihoyoBBS文件解压缩放到scripts中 路径 /mnt/mmcblk2p4/mydata/docker/ql-genshin/scripts ![1](https://user-images.githubusercontent.com/33948765/185609351-678b7d30-e5ab-41c7-ac6e-dfe3279f5a1e.jpg)
> 
> 3. 把配置好的json文件放到config中
>    路径 /mnt/mmcblk2p4/mydata/docker/ql-genshin/scripts/Womsxd_AutoMihoyoBBS/config
>    ![2](https://user-images.githubusercontent.com/33948765/185609367-b945242e-9425-4188-9f76-02012d0206bd.jpg)
> 4. 登录qinglong后 在定时任务 新建任务
>    名称 随意
>    命令 task Womsxd_AutoMihoyoBBS/main_multi.py
>    定时规则 10 1,4,23 * * *
> 
> 上面的定时规则 是每天的 1, 4, 23时 10分的时候开始运行，就是一天运行了3次 ![3](https://user-images.githubusercontent.com/33948765/185609430-3b7ab18c-5f59-483f-a875-8ff746aea15b.jpg)
> 
> 5. 设置环境变量 AutoMihoyoBBS_autorun 1
>    ![5](https://user-images.githubusercontent.com/33948765/185609273-b5ba421c-18e6-4a60-afeb-1a20b4825329.jpg)
> 6. 添加python依赖
>    ![6](https://user-images.githubusercontent.com/33948765/185613266-fa6396f9-9459-4381-95f1-9503267bc42e.jpg)
> 
> ![4](https://user-images.githubusercontent.com/33948765/185609007-6f521b00-2a43-447c-b71a-aea3488214b3.jpg)

感谢解答，我看一下青龙的用法
