### ISSUE TITLE
突然的bug

### ISSUE THREAD

**Issue by BAILE2852** [Womsxd/AutoMihoyoBBS#198]
前几天用的好好的，最近两天运行就报错。
![L1HJO`45 LML2 Y{S3X7XUF](https://user-images.githubusercontent.com/88181881/185743842-c6bed9f4-bc44-4378-8956-c8b9a7bc4a93.png)

**Comment by Womsxd** [comment]
有没有一种可能，你可以下载一下更新来解决这个问题？
