### ISSUE TITLE
咋快速更新版本呀

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#200]
大佬，github更新代码后，我本地咋快速更新呀，有什么比较优雅的方式么

**Comment by Teconheci** [comment]
还有就是要不try catch多写点，有时候直接就碰到异常，导致程序中断，后面的失败推送没有执行{{{(>_<)}}}

**Comment by Womsxd** [comment]
> 大佬，github更新代码后，我本地咋快速更新呀，有什么比较优雅的方式么

推荐使用git来更新，
先用: git clone 仓库地址 来拉取项目
后续可以直接: git pull 进行更新
