### ISSUE TITLE
请问这个报错是怎么回事呢？

### ISSUE THREAD

**Issue by taklele** [Womsxd/AutoMihoyoBBS#202]
报错提示：
<img width="854" alt="json2" src="https://user-images.githubusercontent.com/2526519/185778405-292efa9a-be11-4dea-9f8d-01f527bda8bb.png">

json文件验证：
<img width="345" alt="json" src="https://user-images.githubusercontent.com/2526519/185778410-7f1d0f23-e60d-448e-aa0a-db1b67831168.png">

刚刚更新的docker版本，一直报错，请问怎么修复？

**Comment by Womsxd** [comment]
尝试重新创建docker容器(可保留config文件夹)，或者试试删掉__pycache__文件夹
问题原因是米哈游让旧api失效，脚本已经改用新版本api

**Comment by taklele** [comment]
全部删除重建搞定了，谢谢！
