### ISSUE TITLE
docker下的Ubuntu系统成功运行脚本，但是没有信息推送

### ISSUE THREAD

**Issue by x1737886903** [Womsxd/AutoMihoyoBBS#203]
相当于Linux本地部署，但是没有信息通知
![467D`RBJOR5TU71URG~SV)5](https://user-images.githubusercontent.com/52018129/185792081-60423fbb-099d-4a76-9aec-815ec608355f.png)

**Comment by Womsxd** [comment]
请配置push.ini

**Comment by x1737886903** [comment]
> 

配置了，但是没反应

**Comment by x1737886903** [comment]
解决了，
enable=true
push_server=wecom
这两个参数没改
