### ISSUE TITLE
阿里云FC提示云函数执行，无法保存，这个要开什么权限配置吗。

### ISSUE THREAD

**Issue by lie5860** [Womsxd/AutoMihoyoBBS#206]
云函数执行，无法保存
![image](https://user-images.githubusercontent.com/30894657/185882573-7ecbdfde-46b8-4280-968f-fa86742a743d.png)

**Comment by Womsxd** [comment]
请先本地手动保存运行一遍，或者在云函数控制台手动执行一遍

**Comment by Womsxd** [comment]
云函数在执行的时候无法写文件

**Comment by lie5860** [comment]
可以了~
