### ISSUE TITLE
签到报错了

### ISSUE THREAD

**Issue by Cigarr** [Womsxd/AutoMihoyoBBS#207]
![2022-08-22_191628](https://user-images.githubusercontent.com/56327771/185908825-f77f3813-7350-40fe-9f7a-7d34acaedbad.png)

不知道什么原因

**Comment by Womsxd** [comment]
更新了吗？更新后还不行备份config文件夹重新下载脚本解决

**Comment by Cigarr** [comment]
已解决，谢谢大佬
