### ISSUE TITLE
一直运行正常突然在运行数天后报错

### ISSUE THREAD

**Issue by Bai-soda** [Womsxd/AutoMihoyoBBS#208]
错误报告：

FunctionCompute python3 runtime inited.FC Invoke Start RequestId: 110c9a3d-8208-4b9a-a981-335039bd43f82022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] Config加载完毕2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] 正在获取任务列表2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] 新的一天，今天可以获得90个米游币2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] 正在获取帖子列表......2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] 已获取5个帖子2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [INFO] 正在签到......2022-08-23 07:22:02 110c9a3d-8208-4b9a-a981-335039bd43f8 [ERROR] {    "errorMessage": "Extra data: line 1 column 5 (char 4)",    "errorType": "JSONDecodeError",    "stackTrace": [        [            "File \"/code/index.py\"",            "line 11",            "in main_handler",            "status_code, push_message = main.main()"        ],        [            "File \"/code/main.py\"",            "line 54",            "in main",            "bbs.signing()"        ],        [            "File \"/code/mihoyobbs.py\"",            "line 127",            "in signing",            "data = req.json()"        ],        [            "File \"/var/fc/lang/python3.9/lib/python3.9/site-packages/requests/models.py\"",            "line 910",            "in json",            "return complexjson.loads(self.text, **kwargs)"        ],        [            "File \"/var/fc/lang/python3.9/lib/python3.9/json/__init__.py\"",            "line 346",            "in loads",            "return _default_decoder.decode(s)"        ],        [            "File \"/var/fc/lang/python3.9/lib/python3.9/json/decoder.py\"",            "line 340",            "in decode",            "raise JSONDecodeError(\"Extra data\", s, end)"        ]    ]}FC Invoke End RequestId: 110c9a3d-8208-4b9a-a981-335039bd43f8, Error: Unhandled function error

**Comment by Womsxd** [comment]
更新脚本

**Comment by Bai-soda** [comment]
> 更新脚本

感谢您的回复，问题已解决。
