### ISSUE TITLE
关于崩坏3签到失败的问题

### ISSUE THREAD

**Issue by che77a38** [Womsxd/AutoMihoyoBBS#210]
INFO 正在进行崩坏3签到
INFO 正在获取米哈游账号绑定的崩坏3账号列表...
INFO 已获取到1个崩坏3账号信息
INFO 正在获取签到奖励列表...
INFO 正在为舰长: xxxxx进行签到哦...
WARNING 获取账号签到信息失败！
{"data":null,"message":"请从游戏内打开参与活动","retcode":-100}
请问是什么问题,第一次遇到

**Comment by Womsxd** [comment]
请手动去米游社签到一下
