### ISSUE TITLE
本地可以运行，腾讯云不可以，这是为啥

### ISSUE THREAD

**Issue by jcwongg** [Womsxd/AutoMihoyoBBS#211]
ERROR RequestId: d2525567-b836-4317-8ac4-5e6f61aff9da Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     import main   File "/var/user/main.py", line 3, in <module>     import push   File "/var/user/push.py", line 7, in <module>     from request import http   File "/var/user/request.py", line 3, in <module>     import httpx   File "/var/user/httpx/__init__.py", line 2, in <module>     from ._api import delete, get, head, options, patch, post, put, request, stream   File "/var/user/httpx/_api.py", line 4, in <module>     from ._client import Client   File "/var/user/httpx/_client.py", line 5, in <module>     from contextlib import asynccontextmanager, contextmanager ImportError: cannot import name 'asynccontextmanager'", "statusCode": 443}

END RequestId: d2525567-b836-4317-8ac4-5e6f61aff9da

Report RequestId: d2525567-b836-4317-8ac4-5e6f61aff9da Duration: 0ms Memory: 128MB MemUsage: 10.62MB

START RequestId:d2525567-b836-4317-8ac4-5e6f61aff9da

ERROR RequestId:d2525567-b836-4317-8ac4-5e6f61aff9da Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1, in \u003cmodule\u003e\n    import main\n  File \"/var/user/main.py\", line 3, in \u003cmodule\u003e\n    import push\n  File \"/var/user/push.py\", line 7, in \u003cmodule\u003e\n    from request import http\n  File \"/var/user/request.py\", line 3, in \u003cmodule\u003e\n    import httpx\n  File \"/var/user/httpx/__init__.py\", line 2, in \u003cmodule\u003e\n    from ._api import delete, get, head, options, patch, post, put, request, stream\n  File \"/var/user/httpx/_api.py\", line 4, in \u003cmodule\u003e\n    from ._client import Client\n  File \"/var/user/httpx/_client.py\", line 5, in \u003cmodule\u003e\n    from contextlib import asynccontextmanager, contextmanager\nImportError: cannot import name 'asynccontextmanager'","statusCode":443}

**Comment by Womsxd** [comment]
httpx的关系，你试试删掉httpx开头的文件夹

**Comment by jcwongg** [comment]
我直接跑阿里云了

**Comment by Womsxd** [comment]
> 我直接跑阿里云了

txy没有py3.9环境，然后ssl版本有问题(
阿里云有py3.9问题就不大
