### ISSUE TITLE
运行多账号时报错

### ISSUE THREAD

**Issue by pppabamh** [Womsxd/AutoMihoyoBBS#213]
![Screenshot_2022-08-26-03-34-41-21](https://user-images.githubusercontent.com/106404630/186752851-361bebb9-923a-471f-98c3-f33d00a6da1b.jpg)

**Comment by pppabamh** [comment]
偶尔会报错 有时会有时不会

**Comment by Womsxd** [comment]
看报错的话是网络问题

**Comment by pppabamh** [comment]
> 看报错的话是网络问题

知道了 是丢包太多了
