### ISSUE TITLE
阿里云运行失败

### ISSUE THREAD

**Issue by windskyxb** [Womsxd/AutoMihoyoBBS#214]
返回结果：
{
    "errorMessage": "Unable to import module 'index'",
    "errorType": "ImportModuleError",
    "stackTrace": [
        "ModuleNotFoundError: No module named 'yaml'"
    ]
}
![image](https://user-images.githubusercontent.com/60282327/186792259-a36154f9-4a68-479e-9cb0-439e86880742.png)
日志输出：
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 5038a438-6fb4-433d-ac5d-01b220d99c60
2022-08-26 08:33:05 5038a438-6fb4-433d-ac5d-01b220d99c60 [ERROR] {'errorMessage': "Unable to import module 'index'", 'errorType': 'ImportModuleError', 'stackTrace': ["ModuleNotFoundError: No module named 'yaml'"]}
FC Invoke End RequestId: 5038a438-6fb4-433d-ac5d-01b220d99c60, Error: Unhandled function error
![image](https://user-images.githubusercontent.com/60282327/186792298-4e0286c6-4aaf-4c7f-b693-c572f395e826.png)
根据阿里云建议的解决方案，在终端中运行`pip3 install yaml -t .`，提示：
$pip3 install yaml -t .
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
![image](https://user-images.githubusercontent.com/60282327/186792428-f3c47bd8-fb24-442b-a51f-0f3acd799594.png)
在运行正常的本地文件夹执行`pip install yaml -t .`，提示：
C:\Users\winds\Documents\Codes\AutoMihoyoBBS>pip install yaml -t .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml
WARNING: There was an error checking the latest version of pip.
![image](https://user-images.githubusercontent.com/60282327/186792571-1b6abc41-6432-4183-8c26-306455e3e3e6.png)

**Comment by windskyxb** [comment]
本地正常运行
![image](https://user-images.githubusercontent.com/60282327/186792907-f491c3e1-fb88-411a-906c-8e55ae99db10.png)

**Comment by SeanRao** [comment]
依赖问题，安装yaml的依赖，pip install pyyaml

**Comment by Womsxd** [comment]
安装pyyaml，pyyaml模块导入的时候叫yaml

**Comment by windskyxb** [comment]
感谢，执行`pip install pyyaml -t.`后阿里云函数正常运行了
