### ISSUE TITLE
本地运行正常但是腾讯云函数却运行失败

### ISSUE THREAD

**Issue by wgll000** [Womsxd/AutoMihoyoBBS#218]
本地运行正常但是腾讯云函数却运行失败

START RequestId: c8d087d9-9e46-493b-9002-94667132a3aa

Converted retries value: 10 -> Retry(total=10, connect=None, read=None, redirect=None, status=None)

Converted retries value: 10 -> Retry(total=10, connect=None, read=None, redirect=None, status=None)

Init Report RequestId: c8d087d9-9e46-493b-9002-94667132a3aa Coldstart: 481ms (PullCode: 0ms InitRuntime: 4ms InitFunction: 477ms) Memory: 512MB MemUsage: 16.28MB

ERROR RequestId: c8d087d9-9e46-493b-9002-94667132a3aa Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     import main   File "/var/user/main.py", line 3, in <module>     import push   File "/var/user/push.py", line 10, in <module>     from config import update_config_need   File "/var/user/config.py", line 3, in <module>     import yaml ModuleNotFoundError: No module named 'yaml'", "statusCode": 443}

**Comment by Womsxd** [comment]
在main.py同级目录下运行pip install PyYAML -t .

**Comment by CirnoSalt** [comment]
本机已安装python的前提下，在解压出的脚本目录打开终端运行`pip install -r requirements.txt -t .`这个命令安装依赖到当前目录，之后再重新打包上传。

**Comment by MRMASK006** [comment]
> 在main.py同级目录下运行pip install PyYAML -t .

不论本地还是云服务这边，不论是pip install PyYAML -t还是pip install -r requirements.txt -t，都显示是-t option requires 1 argument

**Comment by Elletear** [comment]
> 在main.py同级目录下运行pip install PyYAML -t .

本地运行正常，腾讯SCF报错（已在main.py同级目录安装PyYAML 即src目录）
error code `ERROR RequestId: 3536c8ac-005b-49be-b7b9-d33a11f8a2d8 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     import main   File "/var/user/main.py", line 3, in <module>     import push   File "/var/user/push.py", line 10, in <module>     from config import update_config_need   File "/var/user/config.py", line 3, in <module>     import yaml   File "/var/user/yaml/__init__.py", line 4, in <module>     from tokens import * ModuleNotFoundError: No module named 'tokens'", "statusCode": 443}`

按此方法

> 本机已安装python的前提下，在解压出的脚本目录打开终端运行`pip install -r requirements.txt -t .`这个命令安装依赖到当前目录，之后再重新打包上传。
则error code 变为 `ERROR RequestId: efa912b3-f992-4ff5-88fe-79a5749ccdef Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     import main   File "/var/user/main.py", line 3, in <module>     import push   File "/var/user/push.py", line 7, in <module>     from request import http   File "/var/user/request.py", line 3, in <module>     import httpx   File "/var/user/httpx/__init__.py", line 2, in <module>     from ._api import delete, get, head, options, patch, post, put, request, stream   File "/var/user/httpx/_api.py", line 4, in <module>     from ._client import Client   File "/var/user/httpx/_client.py", line 5, in <module>     from contextlib import asynccontextmanager, contextmanager ImportError: cannot import name 'asynccontextmanager'", "statusCode": 443}`

**Comment by Womsxd** [comment]
删掉httpx开头的文件夹即可

**Comment by clover1420** [comment]
也可以直接把本地的yaml库文件夹复制到项目根目录，在上传到腾讯云。

**Comment by Womsxd** [comment]
> 也可以直接把本地的yaml库文件夹复制到项目根目录，在上传到腾讯云。

这个问题是httpx的问题，或者说是腾讯云python版本+openssl版本一起导致的问题

**Comment by Womsxd** [comment]
备份config文件夹，然后下载最新源码并执行
pip3 install -r requirements_qcloud.txt -t .

**Comment by clover1420** [comment]
> 备份config文件夹，然后下载最新源码并执行 pip3 install -r requirements_qcloud.txt -t .

我也遇到过这个问题，我把本地yaml库上传上去就好了。
