### ISSUE TITLE
运行后没有看帖点赞分享

### ISSUE THREAD

**Issue by xANoyU** [Womsxd/AutoMihoyoBBS#22]
![image](https://user-images.githubusercontent.com/62326160/136504156-25555c38-a48b-48e9-8338-916bb9e97883.png)
想要完成星穹铁道的讨论区签到和点赞任务，但是似乎直接跳过了，是因为其它版块的都已经完成导致的吗？

**Comment by Womsxd** [comment]
专门用于星穹铁道社区的氵经验脚本我目前还在自己测试中

**Comment by Womsxd** [comment]
请问今天可以了吗
