### ISSUE TITLE
可否增加随机延时？减少被系统风控的几率。

### ISSUE THREAD

**Issue by dextersa** [Womsxd/AutoMihoyoBBS#220]
启动时，增加个随机延时的函数，减少被系统风控的几率。

**Comment by Womsxd** [comment]
不会减少，我甚至随便找个时间人工执行都会，云厂商寄的稍微快一点感觉

**Comment by lansepeach** [comment]
> 不会减少，我甚至随便找个时间人工执行都会，云厂商的IP寄的稍微快一点感觉

家用动态IP签到原神也是百分百寄，刚刚更新了大佬您的程序重新获取了cookie，其他都正常就是原神寄了，Ubuntu 20.04.5 LTS，Python 3.8.10，估计原神项目部的大佬出手了

**Comment by dextersa** [comment]
我更新UA后似乎解决了。
