### ISSUE TITLE
怎么增加点赞帖子的次数

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#228]
mihoyobbs里的那个点赞次数变量改为5，还是只点赞了5次

**Comment by Womsxd** [comment]
self.Task_do["bbs_Like_posts_num"] -= i["happened_times"]
改这里，你直接强行改成10次到这里照样会被覆盖掉

**Comment by Teconheci** [comment]
> self.Task_do["bbs_Like_posts_num"] -= i["happened_times"]
> 改这里，你直接强行改成10次到这里照样会被覆盖掉

直接删除么?但是这个不是要完成的次数是初始次数减去已完成次数么，直接改上面的初始值感觉可以呀

**Comment by Womsxd** [comment]
覆盖掉这个值

**Comment by snacks-yummy** [comment]
> 覆盖掉这个值

您好就是说需要改多少次就直接输入改的次数对吧
