### ISSUE TITLE
能做任务但是不能签到，请问该怎么获取能签到的cookie呢？

### ISSUE THREAD

**Issue by taklele** [Womsxd/AutoMihoyoBBS#229]
![Snipaste_2022-08-29_12-02-27](https://user-images.githubusercontent.com/2526519/187120765-bdd8a663-03ac-4d95-924d-683b330c1b4d.png)

报错如图，谢谢。

**Comment by heyuhua1992** [comment]
建议 使用tool.exe 选4 再选 1，
要放入两个cookie，别漏了

**Comment by taklele** [comment]
> 

请问您说的tool.exe在哪下载？是tool.py吗？

**Comment by taklele** [comment]
> 建议 使用tool.exe 选4 再选 1， 要放入两个cookie，别漏了


请问您说的tool.exe在哪下载？是tool.py吗？

**Comment by Womsxd** [comment]
https://github.com/Womsxd/mihoyo_login

选择3

**Comment by heyuhua1992** [comment]
> > 建议 使用tool.exe 选4 再选 1， 要放入两个cookie，别漏了
> 
> 请问您说的tool.exe在哪下载？是tool.py吗？

搞错了 抱歉 不是同一个程序
