### ISSUE TITLE
使用云原神玩的就签到失败？

### ISSUE THREAD

**Issue by kingke0620** [Womsxd/AutoMihoyoBBS#230]
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 117, in <module>
    config.update_config()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/config.py", line 88, in update_config
    config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
KeyError: 'cloud_genshin'

**Comment by tanmx** [comment]
更新配置文件 添加：
```
cloud_games:
  genshin:
    enable: true
    token: 'xxxxxxxxxxxxx'
```
但是我这运行还是报错
```
2022-08-29T09:34:00 INFO 正在进行云原神签到
Traceback (most recent call last):
  File "/ql/data/scripts/tanmx_AutoMihoyoBBS_master/main.py", line 119, in <module>
    status_code, message = main()
  File "/ql/data/scripts/tanmx_AutoMihoyoBBS_master/main.py", line 105, in main
    data = cloud_ys.sign_account()
  File "/ql/data/scripts/tanmx_AutoMihoyoBBS_master/cloud_genshin.py", line 32, in sign_account
    if req["data"]["free_time"]['free_time'] == '0':
TypeError: 'Response' object is not subscriptable
```

**Comment by Womsxd** [comment]
等下，我修复一下

**Comment by clover1420** [comment]
这是判断的变量用错了，把req["data"]["free_time"]['free_time']改成data["data"]["free_time"]['free_time']就行了

**Comment by Womsxd** [comment]
fix

**Comment by Fidetro** [comment]
```
2022-08-31T00:59:26 INFO AutoMihoyoBBS Multi User mode
2022-08-31T00:59:26 INFO 正在搜索配置文件！
2022-08-31T00:59:26 INFO 已搜索到4个旧版config文件，正在进行升级
2022-08-31T00:59:26 INFO 开始处理beizi.json
2022-08-31T00:59:26 INFO 正在更新config....
2022-08-31T00:59:26 INFO v5Config加载完毕
Traceback (most recent call last):
  File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
    main_multi(autorun)
  File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
    config.update_config()
  File "/home/AutoMihoyoBBS/config.py", line 88, in update_config
    config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
KeyError: 'cloud_genshin'
```
我拉了最新的代码，看起来config更新还是失败

**Comment by TifezzZ** [comment]
> ```
> 2022-08-31T00:59:26 INFO AutoMihoyoBBS Multi User mode
> 2022-08-31T00:59:26 INFO 正在搜索配置文件！
> 2022-08-31T00:59:26 INFO 已搜索到4个旧版config文件，正在进行升级
> 2022-08-31T00:59:26 INFO 开始处理beizi.json
> 2022-08-31T00:59:26 INFO 正在更新config....
> 2022-08-31T00:59:26 INFO v5Config加载完毕
> Traceback (most recent call last):
>   File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
>     main_multi(autorun)
>   File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
>     config.update_config()
>   File "/home/AutoMihoyoBBS/config.py", line 88, in update_config
>     config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
> KeyError: 'cloud_genshin'
> ```
> 
> 我拉了最新的代码，看起来config更新还是失败

这个应该是转换脚本有问题 配置文件从json 换成了 yaml 你可以手动把原来json里的cookie、login_ticket、stuid、stoken粘贴过去 或者 重新获取cookie 生成配置文件即可

**Comment by Womsxd** [comment]
> ```
> 2022-08-31T00:59:26 INFO AutoMihoyoBBS Multi User mode
> 2022-08-31T00:59:26 INFO 正在搜索配置文件！
> 2022-08-31T00:59:26 INFO 已搜索到4个旧版config文件，正在进行升级
> 2022-08-31T00:59:26 INFO 开始处理beizi.json
> 2022-08-31T00:59:26 INFO 正在更新config....
> 2022-08-31T00:59:26 INFO v5Config加载完毕
> Traceback (most recent call last):
>   File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
>     main_multi(autorun)
>   File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
>     config.update_config()
>   File "/home/AutoMihoyoBBS/config.py", line 88, in update_config
>     config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
> KeyError: 'cloud_genshin'
> ```
> 
> 我拉了最新的代码，看起来config更新还是失败

fix 拉取最新代码解决

**Comment by clover1420** [comment]
> ```
> 2022-08-31T00:59:26 INFO AutoMihoyoBBS Multi User mode
> 2022-08-31T00:59:26 INFO 正在搜索配置文件！
> 2022-08-31T00:59:26 INFO 已搜索到4个旧版config文件，正在进行升级
> 2022-08-31T00:59:26 INFO 开始处理beizi.json
> 2022-08-31T00:59:26 INFO 正在更新config....
> 2022-08-31T00:59:26 INFO v5Config加载完毕
> Traceback (most recent call last):
>   File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
>     main_multi(autorun)
>   File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
>     config.update_config()
>   File "/home/AutoMihoyoBBS/config.py", line 88, in update_config
>     config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
> KeyError: 'cloud_genshin'
> ```
> 
> 我拉了最新的代码，看起来config更新还是失败

可以尝试把config.py里的88和89行
config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
config['cloud_genshin']['enable'] = config_json['cloud_genshin']['enable']
这2句注释了试试。

**Comment by Fidetro** [comment]
> > ```
> > 2022-08-31T00:59:26 INFO AutoMihoyoBBS Multi User mode
> > 2022-08-31T00:59:26 INFO 正在搜索配置文件！
> > 2022-08-31T00:59:26 INFO 已搜索到4个旧版config文件，正在进行升级
> > 2022-08-31T00:59:26 INFO 开始处理beizi.json
> > 2022-08-31T00:59:26 INFO 正在更新config....
> > 2022-08-31T00:59:26 INFO v5Config加载完毕
> > Traceback (most recent call last):
> >   File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
> >     main_multi(autorun)
> >   File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
> >     config.update_config()
> >   File "/home/AutoMihoyoBBS/config.py", line 88, in update_config
> >     config['cloud_genshin']['token'] = config_json['cloud_genshin']['token']
> > KeyError: 'cloud_genshin'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我拉了最新的代码，看起来config更新还是失败
> 
> fix 拉取最新代码解决

```
Traceback (most recent call last):
  File "/home/AutoMihoyoBBS/main_multi.py", line 87, in <module>
    main_multi(autorun)
  File "/home/AutoMihoyoBBS/main_multi.py", line 32, in main_multi
    config.update_config()
  File "/home/AutoMihoyoBBS/config.py", line 90, in update_config
    save_config()
  File "/home/AutoMihoyoBBS/config.py", line 134, in save_config
    f.write(yaml.dump(p_config, Dumper=yaml.Dumper, sort_keys=False))
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```
还是会报错，我改成yaml试试 @Womsxd 
拉最新代码之前，有试过注释，会在另外一个地方报错 @clover1420

**Comment by Fidetro** [comment]
已解决，另外之前没留意要安装`PyYAML`拉了最新代码后也报错了
`pip install -r requirements.txt`后正常
