### ISSUE TITLE
关于签到失败的处理，不需要获取ua，在后面添加 miHoYoBBS/2.35.2即可

### ISSUE THREAD

**Issue by zty1017** [Womsxd/AutoMihoyoBBS#236]
![image](https://user-images.githubusercontent.com/57761557/187614431-2c41d4c8-fb9d-4770-b4b0-a82caf1b3927.png)
如上图修改，手上5个账号，修改后这几天签到都正常
![image](https://user-images.githubusercontent.com/57761557/187614719-81d9a898-6104-4943-95d8-e96adcf65b9d.png)

**Comment by Womsxd** [comment]
我是说有没有一种可能，脚本已经添加了miHoYoBBS/2.35.2 
https://github.com/Womsxd/AutoMihoyoBBS/blob/39451f1cb0f731cebf37784c220178f886fb06b2/genshin.py#L22

**Comment by Womsxd** [comment]
无效issues
