### ISSUE TITLE
第二天就不行了，cookie已失效,请重新登录米游社抓取cookie

### ISSUE THREAD

**Issue by xc1988** [Womsxd/AutoMihoyoBBS#239]
FC Invoke Start RequestId: a90f389e-18ad-4788-8070-240d5aa8ed00
2022-09-01 14:34:28 a90f389e-18ad-4788-8070-240d5aa8ed00 [INFO] Config加载完毕
2022-09-01 14:34:28 a90f389e-18ad-4788-8070-240d5aa8ed00 [ERROR] cookie已失效,请重新登录米游社抓取cookie
2022-09-01 14:34:28 a90f389e-18ad-4788-8070-240d5aa8ed00 [INFO] 云函数执行，无法保存
云函数测试支持！

每次当天测试没问题，第二天就不行了.

**Comment by Womsxd** [comment]
确定是无痕模式抓取的吗？

**Comment by xc1988** [comment]
> ？

是无痕模式

**Comment by xc1988** [comment]
> 确定是无痕模式抓取的吗？
是无痕模式

**Comment by xc1988** [comment]
> 有没有可能，你云函数无法保存

我重新上传试试看

**Comment by heyuhua1992** [comment]
你不会在无痕模式 点了退出登录吧

**Comment by xc1988** [comment]
> 你不会在无痕模式 点了退出登录吧

没有点

**Comment by xc1988** [comment]
昨天重新上传了 今天还是失效了

**Comment by clover1420** [comment]
米游社cookie抓取了，就不能在其他地方登录。

**Comment by MRMASK006** [comment]
我遇到过，先从本地跑一遍再上传，解决了

**Comment by YumeAyai** [comment]
楼主解决了吗

**Comment by xc1988** [comment]
> 楼主解决了吗

没有

**Comment by love3937** [comment]
我跟你一样，估计是账号风控了，用别的脚本会提示要验证，只能手动签到了

**Comment by VinceMar** [comment]
需要先在本地运行一遍，再把你本地执行完的程序上传到云函数。本地执行时，程序会编辑config文件里的login_ticket、stuid、stoken这些字段，而云函数的编辑环境和代码运行环境是两个独立的环境，运行环境所做的修改无法同步到你的编辑环境。因此，云函数每次执行读取你的编辑环境的代码时，那些字段都是空的
