### ISSUE TITLE
在最新版本运行下，米游币正常获取，但在每日签到时出现token为空，跳过任务（项目部署在手机终端）

### ISSUE THREAD

**Issue by 2218164692** [Womsxd/AutoMihoyoBBS#243]

**Comment by 2218164692** [comment]
![Screenshot_20220903-103727.jpg](https://user-images.githubusercontent.com/54579793/188252663-8dd43a01-2c76-48d7-a966-1bb01a7527c3.jpg)

**Comment by clover1420** [comment]
配置文件把云原神项的 enable 改为false
