### ISSUE TITLE
青龙面板获取帖子列表报错

### ISSUE THREAD

**Issue by Lemonmous** [Womsxd/AutoMihoyoBBS#250]
> 2022-09-05T13:42:54 INFO AutoMihoyoBBS Multi User mode
> 2022-09-05T13:42:54 INFO 正在搜索配置文件！
> 2022-09-05T13:42:54 INFO 已搜索到4个配置文件，正在开始执行！
> 2022-09-05T13:42:54 INFO 正在执行config.yaml
> 2022-09-05T13:42:54 INFO Config加载完毕
> 2022-09-05T13:42:54 INFO 正在获取任务列表
> 2022-09-05T13:43:09 INFO 似乎还有任务没完成，今天还能获得40
> 2022-09-05T13:43:09 INFO 正在获取帖子列表......
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
>     yield
>   File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 26, in read
>     return self._sock.recv(max_bytes)
>   File "/usr/lib/python3.10/ssl.py", line 1259, in recv
>     return self.read(buflen)
>   File "/usr/lib/python3.10/ssl.py", line 1132, in read
>     return self._sslobj.read(len)
> TimeoutError: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
>     yield
>   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
>     resp = self._pool.handle_request(req)
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
>     raise exc
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
>     response = connection.handle_request(request)
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 90, in handle_request
>     return self._connection.handle_request(request)
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 105, in handle_request
>     raise exc
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 84, in handle_request
>     ) = self._receive_response_headers(**kwargs)
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 148, in _receive_response_headers
>     event = self._receive_event(timeout=timeout)
>   File "/usr/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 177, in _receive_event
>     data = self._network_stream.read(
>   File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 24, in read
>     with map_exceptions(exc_map):
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
>     raise to_exc(exc)
> httpcore.ReadTimeout: The read operation timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 87, in <module>
>     main_multi(autorun)
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 54, in main_multi
>     run_code, run_message = main.main()
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 45, in main
>     bbs = mihoyobbs.Mihoyobbs()
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/mihoyobbs.py", line 45, in __init__
>     self.postsList = self.get_list()
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/mihoyobbs.py", line 107, in get_list
>     req = http.get(url=setting.bbs_List_url.format(setting.mihoyobbs_List_Use[0]["forumId"]),
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1039, in get
>     return self.request(
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 815, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 902, in send
>     response = self._send_handling_auth(
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 930, in _send_handling_auth
>     response = self._send_handling_redirects(
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
>     response = self._send_single_request(request)
>   File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1003, in _send_single_request
>     response = transport.handle_request(request)
>   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
>     with map_httpcore_exceptions():
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ReadTimeout: The read operation timed out

***
请问下有人知道是什么情况吗？

**Comment by hinak0** [comment]
网络超时，检查网络状况。

**Comment by Lemonmous** [comment]
> 网络超时，检查网络状况。

好滴感谢大佬
