### ISSUE TITLE
dockers运行 触发验证码

### ISSUE THREAD

**Issue by jamsrock001** [Womsxd/AutoMihoyoBBS#251]
3个号 这一个号触发验证码  @，请问有办法吗？

![KN46%I3XO19SJX13@C1L`L0](https://user-images.githubusercontent.com/90016575/188532083-76d20389-3978-4227-9fb9-ed5096f40529.png)

**Comment by hinak0** [comment]
暂时无解，可以尝试抓包改ua，也许有效。

**Comment by Womsxd** [comment]
#179 
重复
