### ISSUE TITLE
outlook邮箱错误

### ISSUE THREAD

**Issue by Theresa-0328** [Womsxd/AutoMihoyoBBS#255]
![1](https://user-images.githubusercontent.com/101574559/189143907-0b17b968-8155-410a-aedf-8448abbf04b5.png)
![2](https://user-images.githubusercontent.com/101574559/189143928-edb78f46-33ad-4b24-ac9e-e145abc6fe2c.png)
outlook接受推送邮件时文字没有正确的显示在图片上。

**Comment by hinak0** [comment]
outlook是使用word引擎解析html，对css的支持很差，懒得做兼容了。

**Comment by hinak0** [comment]
> outlook是使用word引擎解析html，对css的支持很差，懒得做兼容了。

什么懒狗
