### ISSUE TITLE
云原神签到

### ISSUE THREAD

**Issue by kuake0** [Womsxd/AutoMihoyoBBS#269]
我把抓的ck填在config文件夹自己创建的一个yaml文件中
大概就是这样子，使用的是青龙面板，但还是一直提示token为空,跳过任务
cloud_games:
  genshin:
    enable: true
    token: 'ai=x;ci=x;oi=xxxxxx;ct=xxxxxx;si=xxxxxx;bi=xxxxxx'

**Comment by Womsxd** [comment]
自己本地执行一下看看
