### ISSUE TITLE
【问题反馈】邮件推送的字体颜色问题

### ISSUE THREAD

**Issue by yo2yoake** [Womsxd/AutoMihoyoBBS#272]
如图，邮件推送的文本为白色，在浅色模式下难以查看
![)%_TNFAFR4O27ROME)ULUNR](https://user-images.githubusercontent.com/88564661/194013538-04b980c2-e39f-4335-848e-507ddcfdcbc6.png)
![2R0P$~MPO_V_D) (QBU_JKN](https://user-images.githubusercontent.com/88564661/194013558-0dcc452b-2400-4a01-89d1-3c51bf2981be.png)
![PK}X0(QCIIM(FO4C4H%N1N0](https://user-images.githubusercontent.com/88564661/194013566-e0bf3bbc-0787-4fcf-9f7b-6198b01331bf.png)

**Comment by hinak0** [comment]
#255 文字是希望被显示在背景图像上的，但是有的邮箱解析对css的支持不好，导致文字内容被挤下去。
