### ISSUE TITLE
请问怎么增加点赞次数

### ISSUE THREAD

**Issue by GardeniaFlower** [Womsxd/AutoMihoyoBBS#276]
现在默认点赞俩次，连米游币任务都完成不了，想改成10次，请问在哪个文件，哪个位置改？？感谢大佬！

**Comment by Womsxd** [comment]
你改成100次都没用，触发验证码了

**Comment by Womsxd** [comment]
温馨提示：
近期米哈游已经给签到和点赞的api上了验证码，多账号用户可能出现除开头两个号以外的账号签到失败(小概率)以及点赞无法完成(一般来说是第三个账号开始出现)的情况
