### ISSUE TITLE
关于解决触发验证码的一些猜想

### ISSUE THREAD

**Issue by BestLemoon** [Womsxd/AutoMihoyoBBS#292]
看了一些issue，都提到了时间这一个关键因素。那么可以做一步到了cron定时随机等待一段时间来模拟每天在不同的时间签到，在请求API时，也加入一些随机延迟，这样或许可行。
由于学业繁忙目前无法写PR，但是实现起来应该不会很困难。

**Comment by Womsxd** [comment]
请求api有随机延时，基本上大部分time.sleep都是random.randint(2,5)的随机延时，我这边服务器挂的话 windows的计划任务程序也配置了指定时间内随机运行一次，目前社区照样验证码

**Comment by BestLemoon** [comment]
> 请求api有随机延时，基本上大部分time.sleep都是random.randint(2,5)的随机延时，我这边服务器挂的话 windows的计划任务程序也配置了指定时间内随机运行一次，目前社区照样验证码

了解了，后续我多找几个人的cookies再研究研究，如果说不是每次必定会触发，那么应该是可以绕过的🤣
