### ISSUE TITLE
青龙面板订阅多账号问题

### ISSUE THREAD

**Issue by hybbin** [Womsxd/AutoMihoyoBBS#294]
之前青龙多账号是用的main_multi.py加task ./mihoyo/main_multi.py autorun命令可以正常使用，最近两天连续出现验证码没法跳过，所以来看看大佬有没有更新，然后偶然看到大佬新增了青龙订阅功能，青龙面板配置了下发现运行配置文件是用的config.yaml这个指定文件，由于之前多配置原因把配置文件名字都修改成了非config名字，所以导致ql_main.py脚本没法适用多账户模式。

![image](https://user-images.githubusercontent.com/39667157/196604897-26d6774f-8b9b-46e5-bf53-a1b8be146eb8.png)

也可能是我没找到多账号运行方式，没找到运行方法。

**Comment by Womsxd** [comment]
那就用老方法，不使用新方法运行就行了

**Comment by hybbin** [comment]
> 那就用老方法，不使用新方法运行就行了

好
