### ISSUE TITLE
怎么在云函数中使用

### ISSUE THREAD

**Issue by fwehdrumny** [Womsxd/AutoMihoyoBBS#30]
怎么在云函数中使用，我看index.py里有关于云函数的东西

**Comment by Womsxd** [comment]
和本地线按照流程跑一次(完全运行一次)，然后打包一下丢云函数运行就行了

**Comment by Womsxd** [comment]
要求云函数有requests库(你可以打包的时候传一份上去)，如果python版本>=3.7的话可以直接用httpx
