### ISSUE TITLE
 获取账号签到信息失败！  ERROR 账号Cookie有问题！

### ISSUE THREAD

**Issue by Asakushen** [Womsxd/AutoMihoyoBBS#312]
{"data":null,"message":"尚未登录","retcode":-100} ERROR 账号Cookie有问题！
作者您好，按照文档打开两个网站后抓的ck还是失效，尝试了很多遍，无痕+正常模式+完全重新登录都无法正常运行。
![error](https://user-images.githubusercontent.com/74193315/204091888-dae278f1-522c-4eff-ac3d-10042b6de97c.png)

**Comment by flyin9sky** [comment]
我也遇到了一样的问题 好像从昨天开始mhy修改了cookie检验机制

**Comment by anshifa958** [comment]
![image](https://user-images.githubusercontent.com/83939886/204125920-ab24c2f3-7a6f-48c7-932c-86c7f480db05.png)
登录后对照这个位置看了一下，通过那串代码获取的cookie好像不是完整的，少了一些项

**Comment by ZZH731019** [comment]
解决了吗

**Comment by ZZH731019** [comment]
我解决了
![image](https://user-images.githubusercontent.com/100362620/204268751-cc2614de-8a02-426d-bff3-19f55e5c811b.png)

**Comment by ZZH731019** [comment]
我解决了，少了这么几个，在复制完的ck后面按照前面的格式填在后面就好了
![image](https://user-images.githubusercontent.com/100362620/204269256-5f3e31c4-4b69-46a3-b4bf-b482ba9d0b09.png)

**Comment by Asakushen** [comment]
感谢！

**Comment by coolxitech** [comment]
> 感谢！

记得关issues哦
