### ISSUE TITLE
怎么抓米游社的ua啊，作者教程只能抓浏览器的

### ISSUE THREAD

**Issue by ZZH731019** [Womsxd/AutoMihoyoBBS#314]

**Comment by coolxitech** [comment]
过程比较复杂，而且需要做反反抓包操作。你在代码里面找找带mihoyo字段的UA

**Comment by Elletear** [comment]
可采用相同方式，只需在米游社發帖時添加UA提取鏈接，然後點擊即可查看。
ep. [ip138](https://www.ip138.com/useragent)

**Comment by CirnoSalt** [comment]
搜索这个帖子，直接链接点进去复制。
![](https://s1.xptou.com/2022/12/03/638b2a982d7c6.jpg)

**Comment by 1332186865** [comment]
![187184892-64f6bc5b-e3bc-4a26-8baa-77a9f41f863b](https://user-images.githubusercontent.com/90539564/211132852-7a78fcfb-da8d-46f2-a1c2-b34af8caa86b.png)
用米游社扫这个码
