### ISSUE TITLE
Cookie抓不出来了

### ISSUE THREAD

**Issue by ZZH731019** [Womsxd/AutoMihoyoBBS#320]
帮别人签到，发现按教程的方法cookie抓完之后少字段，我又重新抓已经配置完了都好的ck，发现少了个Stoken值。
同时原来ck最前面的“UM_distinctid＝”字段如果在只登陆米游社的情况下可以抓到，但米游社和通行证都登陆之后就没了。。。。
还有就是只登陆米游社抓ck发现后面有一串很诡异的东西，也不知道是乱码还是什么，看图吧![IMG_20221203_082021.jpg](https://user-images.githubusercontent.com/100362620/205412267-75836d47-8234-4aac-afcd-71d4f327f0a6.jpg)

最后，我又尝试了另一个项目的抓ck的方法 （没有说大佬项目不好的意思，在这里谢谢大佬了）但惊奇的发现原来ck里的“account_id”字段也没了，说是可以用account_id和UM_distinctid的ck通过内个项目的包的指令登陆获取stoken。。。
谁知道呢，有大佬知道咋搞吗

**Comment by NekoMua** [comment]
我也是

**Comment by oTnTh** [comment]
我自己还没有试过，不过有个线索提供给诸君。

手机端放置米游社的widget，通过抓包的方式，能获得stuid和stoken，有兴趣的话可以试试能不能找到相关接口。

**Comment by NekoMua** [comment]
> 我自己还没有试过，不过有个线索提供给诸君。
> 
> 手机端放置米游社的widget，通过抓包的方式，能获得stuid和stoken，有兴趣的话可以试试能不能找到相关接口。

似乎在留影叙佳期的web页面似乎还有cookie_token的存在，可以去试试

**Comment by anshifa958** [comment]
搬运其他大佬的解决方案：
https://docs.qq.com/doc/DRmdoS2RiU2ttalNC
https://docs.qq.com/doc/DV2tDY2ltSFdtbU9z

**Comment by L1ttleBad** [comment]
> 搬运其他大佬的解决方案： https://docs.qq.com/doc/DRmdoS2RiU2ttalNC https://docs.qq.com/doc/DV2tDY2ltSFdtbU9z

使用第二个网页里的android方法解决了，立竿见影。感谢。
