### ISSUE TITLE
青龙什么时候能支撑多账号

### ISSUE THREAD

**Issue by Loliwy** [Womsxd/AutoMihoyoBBS#321]
希望青龙能支持

**Comment by forchannot** [comment]
一直支持

**Comment by Loliwy** [comment]
我放了多个yaml只运行了第一个账号

**Comment by Loliwy** [comment]
青龙面板，懂青龙面板吗

**Comment by forchannot** [comment]
> 青龙面板，懂青龙面板吗

用了几百年的东西了

**Comment by Loliwy** [comment]
哦吼吼吼，真6呢

**Comment by forchannot** [comment]
自己不会弄不要怪别人
![image](https://user-images.githubusercontent.com/100580891/205582795-6b48eb62-bc6c-445b-bf65-d0dc58d7ea9a.png)

**Comment by Loliwy** [comment]
狗在叫我还要咬两口？

**Comment by forchannot** [comment]
那你自己慢慢等着吧，方法都给你说了，不会用不怪别人

**Comment by coolxitech** [comment]
> 狗在叫我还要咬两口？

问问题就要有问问题的态度，到底是谁在狗叫谁清楚。

**Comment by coolxitech** [comment]
> > > 狗在叫我还要咬两口？
> > 
> > 问问题就要有问问题的态度，到底是谁在狗叫谁清楚。
> 
> 狗真多

![-48d1685d537f184b.jpg](https://user-images.githubusercontent.com/20185794/205598246-2915ae33-4eac-4b91-8a5c-52f73fa481c8.jpg)

**Comment by Loyisa** [comment]
6

**Comment by Bannyfelt13** [comment]
6

**Comment by Hellxd** [comment]
打起来打起来

**Comment by Bannyfelt13** [comment]
> 打起来打起来

小狗！抓到你了！

**Comment by nicklly** [comment]
简单改改main_mulit的代码就能丢青龙上用了😅 还用了几百年的青龙😅
