### ISSUE TITLE
ua问题

### ISSUE THREAD

**Issue by lchypwx** [Womsxd/AutoMihoyoBBS#331]
请教一下，我自己抓到的singin包的ua是
ios：Hyperion/282 CFNetwork/1404.0.4 Darwin/22.3.0
安卓：okhttp/4.9.3
这种ua能用吗

**Comment by scncyyc** [comment]
至少安卓那个不行 你可以多看几个包，正常的ua是这样的：Mozilla/5.0 (Linux; Android 11; M2102K1C Build/RKQ1.201112.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36 miHoYoBBS/2.42.1
或者用米游社扫描那个获取ua网站的二维码，这个方法不用抓包，而且能得到相同的ua
