### ISSUE TITLE
ck抓不全了

### ISSUE THREAD

**Issue by pyh919597378** [Womsxd/AutoMihoyoBBS#37]
大佬，现在用浏览器抓ck抓不到login_ticket，是不是被和谐了

**Comment by Womsxd** [comment]
login_ticket
能抓到，我成功抓到了

**Comment by pyh919597378** [comment]
是的，我发现了，但是要把登录那个米游社的通行证，在抓，在社区抓不到

**Comment by pyh919597378** [comment]
点击头像那边有个米哈游通行证在用浏览器抓能抓到完整的，谢谢大佬的脚本

**Comment by Womsxd** [comment]
> 是的，我发现了，但是要把登录那个米游社的通行证，在抓，在社区抓不到

这个情况老早就出现了

**Comment by pyh919597378** [comment]
嗷嗷，我刚刚看了一下，大佬你这边是两步，是我自己看岔了，打扰大佬了，不好意思。
