### ISSUE TITLE
本地测试

### ISSUE THREAD

**Issue by 183452584** [Womsxd/AutoMihoyoBBS#40]
直接提示config未启用
![image](https://user-images.githubusercontent.com/47927966/145283556-9d3e91c7-67a2-4770-9c7b-b669b644f4bb.png)

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/blob/master/config/README.md

**Comment by 183452584** [comment]
咋启用呢？需要改那些可以说一下吗？

**Comment by Womsxd** [comment]
> 咋启用呢？需要改那些可以说一下吗？

检查
enable_Config是否为true

**Comment by Womsxd** [comment]
配置文件开启是
"enable_Config": true,

**Comment by 183452584** [comment]
![image](https://user-images.githubusercontent.com/47927966/145513170-7d092bb2-2684-4199-96c6-b7e51b350ea9.png)
请问一下这个是啥意思

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/47927966/145513170-7d092bb2-2684-4199-96c6-b7e51b350ea9.png) 请问一下这个是啥意思

不是，你动了啥，你要动的是.json格式的文件啊，建议重新下载项目，重新配置

**Comment by 183452584** [comment]
谢谢已经成功了，怪我太蠢，这个我之前直接重命名了config.json.example

**Comment by 183452584** [comment]
![image](https://user-images.githubusercontent.com/47927966/145574681-dea94f0c-466b-405d-98c1-d6295aef68b3.png)
这是什么情况
