### ISSUE TITLE
如何使用sever酱 简易推送脚本？

### ISSUE THREAD

**Issue by CorkFyv** [Womsxd/AutoMihoyoBBS#42]
在推送脚本中填入了自己的Sendkey也没有sever酱推送
![HQC_P5N@A1 ~_~W7JF _K51](https://user-images.githubusercontent.com/68682502/145676922-29ae08d1-2d41-439a-af4c-67276f8f9372.png)

**Comment by Womsxd** [comment]
改成执行这个脚本（

**Comment by CorkFyv** [comment]
怎么改？

**Comment by CorkFyv** [comment]
> 在推送脚本中填入了自己的Sendkey也没有sever酱推送 ![HQC_P5N@A1 ~_~W7JF _K51](https://user-images.githubusercontent.com/68682502/145676922-29ae08d1-2d41-439a-af4c-67276f8f9372.png)

**Comment by CorkFyv** [comment]
怎么改？

**Comment by Womsxd** [comment]
> 怎么改？

执行push_main-server.py

**Comment by Mugenhasen** [comment]
请问能支持pushplus推送吗，把pushplus的key塞进去有用吗

**Comment by Womsxd** [comment]
给文档，我改一下就行了

**Comment by Womsxd** [comment]
我今天更新一下推送脚本吧，把push++支持给加上

**Comment by Womsxd** [comment]
> 请问能支持pushplus推送吗，把pushplus的key塞进去有用吗

已经支持

**Comment by xcc3641** [comment]
> > 怎么改？
> 
> 执行push_main-server.py

在云函数里如何执行签到后执行这个脚本？

**Comment by Womsxd** [comment]
> > > 怎么改？
> > 
> > 
> > 执行push_main-server.py
> 
> 在云函数里如何执行签到后执行这个脚本？

等后续修改推送相关的功能吧。。。近期应该会做调整，目前打算内置到脚本里面

**Comment by Womsxd** [comment]
> > > 怎么改？
> > 
> > 
> > 执行push_main-server.py
> 
> 在云函数里如何执行签到后执行这个脚本？

可以使用最新版了~推送脚本已经合并进去了~
只需要把 config/push.ini 里面的`enable`改为`true`，并选择相关推送服务和填入推送密钥即可，server酱就`push_server=ftqq`，pushplus就是`push_server=pushplus`，密钥填到`push_token`就行了

**Comment by CorkFyv** [comment]
> > > > 怎么改？
> > > 
> > > 
> > > 执行push_main-server.py
> > 
> > 在云函数里如何执行签到后执行这个脚本？
> 
> 可以使用最新版了~  推送脚本已经合并进去了
> 只需要把 config/push.ini 里面的`enable`改为`true`，并选择相关推送服务和填入推送密钥即可，server酱就`push_server=ftqq`，pushplus就是`push_server=pushplus`，密钥填到`push_token`就行了
> 如果没有的话就先复制config/push.ini.example并把复制后的改名为config/push.ini

新版本在电脑本地执行`python main.py`有server酱推送，上传到云函数上执行方法`index.main_handler`又没推送了。不知道怎么回事

**Comment by Womsxd** [comment]
> > > > > 怎么改？
> > > > 
> > > > 
> > > > 执行push_main-server.py
> > > 
> > > 
> > > 在云函数里如何执行签到后执行这个脚本？
> > 
> > 
> > 可以使用最新版了~  推送脚本已经合并进去了
> > 只需要把 config/push.ini 里面的`enable`改为`true`，并选择相关推送服务和填入推送密钥即可，server酱就`push_server=ftqq`，pushplus就是`push_server=pushplus`，密钥填到`push_token`就行了
> > 如果没有的话就先复制config/push.ini.example并把复制后的改名为config/push.ini
> 
> 新版本在电脑本地执行`python main.py`有server酱推送，上传到云函数上执行方法`index.main_handler`又没推送了。不知道怎么回事

可改用main_handler_mulit或者使用最新版的index.py替换过去就行了~
之前疏忽了单用户这边的一点小问题

**Comment by CorkFyv** [comment]
> > > > > > > 怎么改？
> > > > > > 
> > > > > > 
> > > > > > 执行push_main-server.py
> > > > > 
> > > > > 
> > > > > 在云函数里如何执行签到后执行这个脚本？
> > > > 
> > > > 
> > > > 可以使用最新版了~  推送脚本已经合并进去了
> > > > 只需要把 config/push.ini 里面的`enable`改为`true`，并选择相关推送服务和填入推送密钥即可，server酱就`push_server=ftqq`，pushplus就是`push_server=pushplus`，密钥填到`push_token`就行了
> > > > 如果没有的话就先复制config/push.ini.example并把复制后的改名为config/push.ini
> > > 
> > > 
> > > 新版本在电脑本地执行`python main.py`有server酱推送，上传到云函数上执行方法`index.main_handler`又没推送了。不知道怎么回事
> > 
> > 可改用main_handler_mulit或者使用最新版的index.py替换过去就行了~ 之前疏忽了单用户这边的一点小问题
> 
> 我这里使用了最新的 index.py 也改动了 push.ini 配置。
> 
> ```
> [setting]
> enable=true
> #共有 cqhttp ftqq(sever酱) pushplus
> push_server=ftqq
> #server酱和pushplus的推送token
> push_token=****
> ```
> 
> 无论本地执行，或者云函数我都没有收到 server 的推送消息。
> 
> btw，该 token 是合法的，在其他项目中收到了消息~
> 
> 我该如何排查这个问题呢？
> 
> 

应该是server酱key错了吧

**Comment by xcc3641** [comment]
> > > > > > > > 怎么改？
> > > > > > > 
> > > > > > > 
> > > > > > > 执行push_main-server.py
> > > > > > 
> > > > > > 
> > > > > > 在云函数里如何执行签到后执行这个脚本？
> > > > > 
> > > > > 
> > > > > 可以使用最新版了~  推送脚本已经合并进去了
> > > > > 只需要把 config/push.ini 里面的`enable`改为`true`，并选择相关推送服务和填入推送密钥即可，server酱就`push_server=ftqq`，pushplus就是`push_server=pushplus`，密钥填到`push_token`就行了
> > > > > 如果没有的话就先复制config/push.ini.example并把复制后的改名为config/push.ini
> > > > 
> > > > 
> > > > 新版本在电脑本地执行`python main.py`有server酱推送，上传到云函数上执行方法`index.main_handler`又没推送了。不知道怎么回事
> > > 
> > > 
> > > 可改用main_handler_mulit或者使用最新版的index.py替换过去就行了~ 之前疏忽了单用户这边的一点小问题
> > 
> > 
> > 我这里使用了最新的 index.py 也改动了 push.ini 配置。
> > ```
> > [setting]
> > enable=true
> > #共有 cqhttp ftqq(sever酱) pushplus
> > push_server=ftqq
> > #server酱和pushplus的推送token
> > push_token=****
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 无论本地执行，或者云函数我都没有收到 server 的推送消息。
> > btw，该 token 是合法的，在其他项目中收到了消息~
> > 我该如何排查这个问题呢？
> 
> 应该是server酱key错了吧

是说 token 吗？我在另外一个签到项目中也是用的该 token 是没有错误的~

**Comment by xcc3641** [comment]
是说还需要在 `push_main-server` 里填写 SendKey 吗？我以为在 push.ini 配置好就完了

**Comment by Womsxd** [comment]
> 是说还需要在 `push_main-server` 里填写 SendKey 吗？我以为在 push.ini 配置好就完了

push_main相关的两个脚本是历史残留，与push.ini无关

**Comment by Womsxd** [comment]
cqhttp和server酱我都测试过了是可以正常使用的
