### ISSUE TITLE
原神不能签到

### ISSUE THREAD

**Issue by drophair** [Womsxd/AutoMihoyoBBS#45]
![image](https://user-images.githubusercontent.com/60098431/146313269-e3212202-d865-4adc-9438-ef7d84df55cf.png)  
***  
这是第二个账号，第一个账号正常没有异常
求解，不知道是什么原因，米游币是可以得到的，只有原神不能签到，

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/60098431/146313269-e3212202-d865-4adc-9438-ef7d84df55cf.png)
> 
> 这是第二个账号，第一个账号正常没有异常 求解，不知道是什么原因，米游币是可以得到的，只有原神不能签到，

进隐身模式重新抓取bbs那边的cookie
