### ISSUE TITLE
希望改一下，多账号可以不用按enter

### ISSUE THREAD

**Issue by SNAKEXGC** [Womsxd/AutoMihoyoBBS#46]
用其他工具的时候，比如青龙如果要按enter就不能正常进行，希望如果按enter不是必须的话，能否考虑移除一下，感谢大佬提供的这么好的项目！！！大佬辛苦了！

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/issues/33#issuecomment-986031263

**Comment by Womsxd** [comment]
设置一个环境变量就行了
