### ISSUE TITLE
readme中 执行 pip install -r requirements.txt 安装模块 未能成功

### ISSUE THREAD

**Issue by DarkKnightReturn** [Womsxd/AutoMihoyoBBS#49]
![powershell](https://user-images.githubusercontent.com/96909753/148719373-e61b32d4-edfc-45f0-9f6b-3959c97a050b.png)
如上图，在解压目录中打开powershell后执行不了那个安装模块，请求大佬帮助~(～￣▽￣)～

**Comment by Womsxd** [comment]
> ![powershell](https://user-images.githubusercontent.com/96909753/148719373-e61b32d4-edfc-45f0-9f6b-3959c97a050b.png) 如上图，在解压目录中打开powershell后执行不了那个安装模块，请求大佬帮助~(～￣▽￣)～

已经安装Python3.x系列？
请试试改用cmd，在powershell里面 start cmd，然后在cmd里执行操作试试

**Comment by Womsxd** [comment]
看样子也有可能是缺少环境变量

**Comment by DarkKnightReturn** [comment]
多谢大佬，刚才重装了一遍python，然后装的时候勾选了环境变量那一框之后可以执行了d=====(￣▽￣*)b

**Comment by ZaichunLi** [comment]
![image](https://user-images.githubusercontent.com/110941152/184066260-0cbc0b60-68cd-452e-9131-fc7d54d21c58.png)
你好，环境变量是有的，但还是安装不了模块，请问一下怎么解决，谢谢！
![image](https://user-images.githubusercontent.com/110941152/184066493-4aeb0091-869e-4aad-ba32-aff8b0097c4f.png)
![image](https://user-images.githubusercontent.com/110941152/184066539-8a112de4-a833-4a72-a50f-b88320b1331f.png)
