### ISSUE TITLE
米游社接口返回数据更新了

### ISSUE THREAD

**Issue by TokisakiYuu** [Womsxd/AutoMihoyoBBS#51]
这个已经没法获取每日未完成的任务了
https://github.com/Womsxd/AutoMihoyoBBS/blob/a4de4cb5c0f5f580416a33cfb39edd2d632ccfc4/mihoyobbs.py#L48-L54

现在这个接口可以拿所有任务
```
https://api-takumi.mihoyo.com/apihub/wapi/getMissions?point_sn=myb
```
不知道是不是更新的

**Comment by Womsxd** [comment]
可以正常获取啊~
请问是碰到了什么问题吗？

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/148915550-8add10c0-7ec5-4cf5-b12f-764b3249486c.png)

**Comment by TokisakiYuu** [comment]
我拿收到的states列表里面是最小是从`mission_id 62 `开始的，不知道咋回事

**Comment by Womsxd** [comment]
> > ![image](https://user-images.githubusercontent.com/45663319/148915550-8add10c0-7ec5-4cf5-b12f-764b3249486c.png)
> 
> 我拿收到的states列表里面是最小是从`mission_id 62 `开始的，不知道咋回事

那是因为这个任务没做吧，我抓取的地方是在米游社 我的 这里进行抓取的

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/blob/9dcb3f0f4eda9ca37a07f97cb446b712bb4200b9/setting.py#L50
这个api来自米游社 我的 版块进行抓取的

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/blob/9dcb3f0f4eda9ca37a07f97cb446b712bb4200b9/mihoyobbs.py#L71-73
在这里我判断获取到的第一个id是否大于或等于62，当满住条件的时候就证明今天的日常任务还没做

**Comment by TokisakiYuu** [comment]
> > > ![image](https://user-images.githubusercontent.com/45663319/148915550-8add10c0-7ec5-4cf5-b12f-764b3249486c.png)
> > 
> > 
> > 我拿收到的states列表里面是最小是从`mission_id 62 `开始的，不知道咋回事
> 
> 那是因为这个任务没做吧，我抓取的地方是在米游社 我的 这里进行抓取的，执行了才会加入这个列表，加上固定4个任务我就直接判断第一个是否是62了

看懂了唉，是我看到这没理顺你的逻辑，打扰了😛

**Comment by TokisakiYuu** [comment]
我在看你的python代码用js自己实现，我不会pyhon眼拙了，哈哈哈
