### ISSUE TITLE
希望支持云原神

### ISSUE THREAD

**Issue by Barry04** [Womsxd/AutoMihoyoBBS#52]
希望支持云原神

**Comment by Womsxd** [comment]
https://github.com/Womsxd/CloudGenshinHelper/blob/6d4858d43dbf7e6f3362ced1a4d05a46ef2e8482/cloud_genshin.py#L70
是这个api吗？

**Comment by Barry04** [comment]
是的。你不写我都打算自己整一个了

**Comment by Barry04** [comment]
你的使用说明希望更加完善些，这样对第一次使用你的项目的人更加友好一些。

**Comment by Womsxd** [comment]
> 你的使用说明希望更加完善些，这样对第一次使用你的项目的人更加友好一些。

我记得账号token是一天左右就失效了的吧？

**Comment by Womsxd** [comment]
我之前开始的时候是有抓包过云原神的接口写过一个自动抢资格的脚本，但好像token容易失效，现在改了？

**Comment by Barry04** [comment]
自动签到和你说的抢资格的不一样可能，我看到genshinhelper是支持的。

**Comment by Womsxd** [comment]
> 自动签到和你说的抢资格的不一样可能，我看到genshinhelper是支持的。

签到相关的api是有进行过抓取的，都是依赖header头的内容，我最近再进行一下测试吧

**Comment by Barry04** [comment]
嗯嗯。我最近没事，我自己也测试看看能不能搞出来

**Comment by TingHsi** [comment]
云原神正式对外开放了，这个issue可以关了
