### ISSUE TITLE
Telegram 推送

### ISSUE THREAD

**Issue by NopeHope133** [Womsxd/AutoMihoyoBBS#53]
请问可以支持 telegram bot 推送吗，比较方便查看运行结果。

以及能不能发一下用到的域名，我需要加到clash白名单。我自己没有设备来查看这个。

**Comment by Womsxd** [comment]
最新版已添加~
https://github.com/Womsxd/AutoMihoyoBBS/blob/master/config/push.ini.example
相关设置请参考push.ini~
