### ISSUE TITLE
通知内容

### ISSUE THREAD

**Issue by NonCheng** [Womsxd/AutoMihoyoBBS#54]
请问  能否在通知里加入比如
签到米游币  总共米游币  签到原神奖励
等信息

只有一个脚本已运行显得很单调

**Comment by Womsxd** [comment]
请问是单用户还是多用户？

**Comment by Womsxd** [comment]
这些需要是可以单用户是可以加入进去，但是多用户那边的话可能不会加入了

**Comment by NonCheng** [comment]
单用户

**Comment by NonCheng** [comment]
这是我想要的样子
![Screenshot_20220129-144516](https://user-images.githubusercontent.com/70121951/151650796-08bd5246-f46d-4961-b5ad-08e4f233e54e.png)
![Screenshot_20220129-144519](https://user-images.githubusercontent.com/70121951/151650799-0ea6ef90-070e-455f-a968-a34df7bd64cc.png)

这是目前的单调的样子
![Screenshot_20220129-144631](https://user-images.githubusercontent.com/70121951/151650824-40fe03e9-46fa-4a16-8643-20697d624c6c.png)

**Comment by Womsxd** [comment]
行，我优化一下单用户这边吧

**Comment by Womsxd** [comment]
但是输出的内容估计没这么丰富

**Comment by NonCheng** [comment]
谢谢啦

**Comment by Womsxd** [comment]
已更新推送内容~

**Comment by NonCheng** [comment]
嗯 谢谢

**Comment by NonCheng** [comment]
> 「米游社脚本」执行成功!
> 米游社：
> 今天已经全部完成了！一共获得100个米游币，目前有430个米游币
> 原神：
> 旅行者：xx已连续签到29天，今天获得的奖励是摩拉x5000
> 崩坏3签到功能未启用！

能否改成

> 「米游社脚本」执行成功！
> 
> 米游社：今天已经全部完成了！
> 一共获得100个米游币
> 目前有430个米游币
> 
> 原神：
> xx已连续签到29天
> 今天获得的奖励是摩拉x5000
> 
> 崩坏3签到功能未启用！

注意原文本中有一个英文叹号
(既然崩坏3没开  不如直接不显示

**Comment by Womsxd** [comment]
已修改

**Comment by Womsxd** [comment]
已修改

**Comment by NonCheng** [comment]
嗯 谢谢啦
