### ISSUE TITLE
云函数和本地使用时出现的推送不一样，并且结果错误

### ISSUE THREAD

**Issue by kannazuki2017** [Womsxd/AutoMihoyoBBS#58]
我看了一下代码，云函数从index启动和本地从main启动的推送方式是不一样的，建议确认一下index.py的第9行，status_code在接收main.main()的返回值后类型为tuple，是否需要修改成与main.py中一致的推送写法。

**Comment by Womsxd** [comment]
恩，我现在已经更新index.py了
