### ISSUE TITLE
原神签到通知错误

### ISSUE THREAD

**Issue by NonCheng** [Womsxd/AutoMihoyoBBS#59]
![IMG_20220207_094244_699](https://user-images.githubusercontent.com/70121951/152712377-80b1159f-d0c9-4cd9-b801-24583d01d367.jpg)
这是真实的

![IMG_20220207_094228_499](https://user-images.githubusercontent.com/70121951/152712417-98ccaa48-b998-4c2c-aa79-70153b934b8d.jpg)
这是脚本通知推送的

时间对不上  物品也对不上

**Comment by Womsxd** [comment]
懂了，retcode为0的时候没+1，如果是打印出来的log的话就是正常的

**Comment by NonCheng** [comment]
奖励内容正确了  可是签到天数依然不对
我感觉签到天数的机制是我运行一次累加一天（？

**Comment by Womsxd** [comment]
> 奖励内容正确了 可是签到天数依然不对 我感觉签到天数的机制是我运行一次累加一天（？

除保存配置外没本地写文件操作了，估计是感觉是从0开始？

**Comment by Womsxd** [comment]
如果从0开始，一切就有合理了（

**Comment by NonCheng** [comment]
有道理
我去看了看  上个月的数据也是少了一天
😂

**Comment by NonCheng** [comment]
现在更新后依然存在这个问题

**Comment by Womsxd** [comment]
这个陈年Bug现在修复了（

**Comment by windskyxb** [comment]
> 这个陈年Bug现在修复了（

现在崩坏3签到的天数又不对了
![fd3b32789223c79c754a103e98737a8](https://user-images.githubusercontent.com/60282327/173287920-133aa733-713d-4224-beb3-58909873563e.png)

**Comment by Womsxd** [comment]
> > 这个陈年Bug现在修复了（
> 
> 现在崩坏3签到的天数又不对了 ![fd3b32789223c79c754a103e98737a8](https://user-images.githubusercontent.com/60282327/173287920-133aa733-713d-4224-beb3-58909873563e.png)

现在应该没问题了，都一套代码了
