### ISSUE TITLE
米游社cookie中现在似乎不含有login_ticket,login_uid字段

### ISSUE THREAD

**Issue by Mark9804** [Womsxd/AutoMihoyoBBS#6]
这两天发现自己之前用的签到脚本炸了，过来投奔了（）

但是熟练的注销重新登录抓完cookie之后发现cookie里已经找不到login_ticket字段了，并且cookie格式似乎也和之前的不太一样（我这边Chrome浏览器可以正常登录）

旧cookie格式：
```
_MHYUUID=xxx; 
mi18nLang=zh-cn; 
login_uid=xxx; 
login_ticket=xxx; 
account_id=xxx; 
cookie_token=xxx; 
ltoken=xxx; 
ltuid=xxx
```

新cookie格式：
```
_MHYUUID=yyy; 
mi18nLang=en-us; (我人在海外，系统默认英文)
ltoken=xxx; 
ltuid=xxx; 
cookie_token=xxx; 
account_id=xxx
```
少了`login_uid`和`login_ticket`两个参数，甚至与账号强绑定的[米游社大地图](https://webstatic.mihoyo.com/app/ys-map-cn/index.html)页面请求也找不到这两个参数

不知道是不是我的个例问题

**Comment by Womsxd** [comment]
抓取的地方变了，需要从两个地方进行抓取了
一个还是bbs那边，另外一个是
user.mihoyo.com
剩下的字段可以在这里进行抓取

**Comment by Womsxd** [comment]
大概7月底左右就GG了吧，8月初发现的问题，我先是抓包米游社解决，然后发现user.mihoyo.com这边也可以获取到剩余的字段

**Comment by Mark9804** [comment]
刚刚尝试了一下[user.mihoyo.com](https://user.mihoyo.com)，发现参数还是缺失的

诡异的来了，打开user之后再打开bbs，从bbs这边获取的cookie参数就完整了，整个过程没有重新登录

虽然不知道为什么，但总之通过奇怪的方式解决了问题

**Comment by Womsxd** [comment]
实际上就是很奇怪，我这边是先bbs再user，也是完全没有问题的
