### ISSUE TITLE
云函数多人签到失败

### ISSUE THREAD

**Issue by mawMOBai** [Womsxd/AutoMihoyoBBS#64]
云函数多人签到失败，貌似报错找不到config.json。请问如何修改

`执行日志
START RequestId: af89cb7e-2a4a-422b-81cc-ab3cfb498599

Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None, status=None)

Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None, status=None)

Init Report RequestId: af89cb7e-2a4a-422b-81cc-ab3cfb498599 Coldstart: 865ms (PullCode: 114ms InitRuntime: 8ms InitFunction: 743ms) Memory: 128MB MemUsage: 16.49MB

ERROR RequestId:af89cb7e-2a4a-422b-81cc-ab3cfb498599 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 9, in main_handler\n    status_code, push_message = main.main()\n  File \"/var/user/main.py\", line 17, in main\n    config.load_config()\n  File \"/var/user/config.py\", line 45, in load_config\n    with open(config_Path, \"r\") as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/var/user/config/config.json'","statusCode":430}

END RequestId:af89cb7e-2a4a-422b-81cc-ab3cfb498599

Report RequestId:af89cb7e-2a4a-422b-81cc-ab3cfb498599 Duration:1ms Memory:128MB MemUsage:16.370537MB`

**Comment by Womsxd** [comment]
main_handler改成main_handler_mulit

**Comment by Womsxd** [comment]
main_handler是单用户

**Comment by mawMOBai** [comment]
你好 云函数修改以后执行依然出错，麻烦看一看

`daman.json执行完毕

正在执行xiaoman.json

Config加载完毕

Starting new HTTPS connection (1): webapi.account.mihoyo.com:443

https://webapi.account.mihoyo.com:443 "GET /Api/cookie_accountinfo_by_loginticket?login_ticket=W0x1yHyWbzpufWB7IvLSKNnWJPb2sEyqJTu6CTZY HTTP/1.1" 200 542

https://api-takumi.mihoyo.com:443 "GET /auth/api/getMultiTokenByLoginTicket?login_ticket=W0x1yHyWbzpufWB7IvLSKNnWJPb2sEyqJTu6CTZY&token_types=3&uid=303466359 HTTP/1.1" 200 184

登录成功！

正在保存Config！

ERROR RequestId:a2f4f090-da2a-4537-99cc-1079a05f540a Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 19, in main_handler_mulit\n    main_multi.main_multi(True)\n  File \"/var/user/main_multi.py\", line 43, in main_multi\n    run_code, run_message = main.main()\n  File \"/var/user/main.py\", line 23, in main\n    login.login()\n  File \"/var/user/login.py\", line 28, in login\n    config.save_config()\n  File \"/var/user/config.py\", line 75, in save_config\n    with open(config_Path, \"r+\") as f:\nOSError: [Errno 30] Read-only file system: '/var/user/config/xiaoman.json'","statusCode":430}

END RequestId:a2f4f090-da2a-4537-99cc-1079a05f540a

Report RequestId:a2f4f090-da2a-4537-99cc-1079a05f540a Duration:26436ms Memory:128MB MemUsage:17.852959MB`

**Comment by Womsxd** [comment]
请本地执行一次脚本来获取/生成完整的配置文件再上传云函数

**Comment by Womsxd** [comment]
python main_multi.py

**Comment by mawMOBai** [comment]
完美解决，谢谢！
