### ISSUE TITLE
云函数，不知道哪里错了

### ISSUE THREAD

**Issue by Edm-best** [Womsxd/AutoMihoyoBBS#65]
![image](https://user-images.githubusercontent.com/65123215/156511120-16d108b7-68be-4f46-9976-c25f7e8c4d44.png)
大佬看看啥错了

**Comment by Womsxd** [comment]
请本地执行一次脚本来获取完整的配置文件再上传云函数

**Comment by dafengshu123** [comment]
![image](https://user-images.githubusercontent.com/93378119/160517373-d05bc3f0-182c-4cc0-a8ff-41c23c93b2df.png)
本地能运行，上传到云函数就报错

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/93378119/160517373-d05bc3f0-182c-4cc0-a8ff-41c23c93b2df.png) 本地能运行，上传到云函数就报错

没找到config.json
