### ISSUE TITLE
cookie失效无通知

### ISSUE THREAD

**Issue by ax1742** [Womsxd/AutoMihoyoBBS#66]
前几天在Linux服务器里用docker部署了这个项目，今天想着再弄一个crontab定时签到，然后测试的时候一直失败，花了十几分钟才找到原因，一直以为是docker的问题，后面才想到有没有可能是cookie过期的原因，更新cookie后果然解决了，main.py下有判断cookie的代码，但不知道为什么没通知

**Comment by Womsxd** [comment]
看执行的版本吧，单用户的推送和多用户有点不一样

**Comment by Womsxd** [comment]
「米游社脚本」执行成功!
脚本执行完毕，共执行xx个配置文件，成功xxx个，没执行x个，失败x个
没执行的配置文件: ['xx.json', 'xx.json']
执行失败的配置文件: ['xx.json','xx.json']

**Comment by Womsxd** [comment]
好改，这个问题，看了下推送，main.py这里有抛出异常，我修改一下这里就ok了
![image](https://user-images.githubusercontent.com/45663319/156884732-6c164986-9066-4cb6-9c72-77bf78918783.png)

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/156884776-1b5a0f30-87f2-45cf-bc39-7695c55e9ce5.png)
这里是修完成的代码逻辑，第一次cookie出错后会直接提示出错，后续会抛出config未启用的提示

**Comment by Womsxd** [comment]
如果有不妥的可以来提交反馈
