### ISSUE TITLE
腾讯云函数超时问题？

### ISSUE THREAD

**Issue by wangzboo** [Womsxd/AutoMihoyoBBS#67]
![image](https://user-images.githubusercontent.com/39321118/157872779-a7d23238-3ccd-49ab-9a6a-2525895db329.png)

**在本地执行成功，放到linux服务器也成功**

![image](https://user-images.githubusercontent.com/39321118/157872944-f1056eff-0eaf-47e1-90e6-c0918b754bb9.png)

**但是放到腾讯云函数上报错了，错误如下**

![image](https://user-images.githubusercontent.com/39321118/157873202-876705cd-64e0-43e2-9d95-a14e43f69e0c.png)

**请大佬帮忙看一下，是否是因为3000ms超时的原因呢？**

**另外阿里云的云函数，我只看到支持node.js没看到支持python，请问在哪里使用呢？**

**Comment by Womsxd** [comment]
能提供一下完整的执行日志麻？腾讯云云函数python3.7版本不会自带requests包，如果是3.7请降级到3.6

**Comment by Womsxd** [comment]
感觉是没requests或httpx包，脚本是优先使用httpx，当httpx无法使用的时候会改用requests

**Comment by wangzboo** [comment]
**我换成阿里的可以用了，但是代码里头的一个函数名称需要修改一下**

![image](https://user-images.githubusercontent.com/39321118/158006718-5d712015-bdc8-4a71-8fa0-70207dce7d7a.png)

**需要将这个位置的main_handler改为my_handler，官方文档可能更新了这个地方。**

![image](https://user-images.githubusercontent.com/39321118/158006756-e45ce4f3-749d-49a2-b3c0-921841183161.png)

**Comment by Womsxd** [comment]
这个简单，直接新建一个my_handler然后调用main_handler就完事了

**Comment by Womsxd** [comment]
刚再次看了下，还真是超时的问题，推荐脚本一个号70s
