### ISSUE TITLE
多账号执行通知推送没有具体内容

### ISSUE THREAD

**Issue by fengyec2** [Womsxd/AutoMihoyoBBS#75]
多账号执行通知推送没有具体内容，云函数。
<img width="377" alt="Snipaste_2022-04-09_12-42-17" src="https://user-images.githubusercontent.com/85821538/162556726-07ef6ba1-9466-442f-b0a0-f1dfb869a7b7.png">

**Comment by Womsxd** [comment]
需要多详细？输出这么点是刻意的(

**Comment by Womsxd** [comment]
请问有后续想法吗？

**Comment by Teconheci** [comment]
> 

简单点也好
