### ISSUE TITLE
请问项目写了每天自动执行的任务吗

### ISSUE THREAD

**Issue by ShoodramWu** [Womsxd/AutoMihoyoBBS#78]
看tools.py有获取下一次时间戳的函数
requirements.txt里也有crond
先说下我的执行环境，丢到centos云服务器上，目前手写了crond任务
45 00 * * * /usr/bin/python3 /root/AutoMihoyoBBS-master/main.py >> /var/log/AutoMihoyoBBS/$(date "+%Y%m").log  2>&1
如果项目有自动执行功能，就没必要多此一举了

**Comment by Womsxd** [comment]
没有，这个代码是之前的遗留，现在依赖crond或者计划任务程序来自动执行

**Comment by ShoodramWu** [comment]
可以在readme上加上关于crond的说明，不然本地运行的同学可能会对程序有误解
还有程序有记录运行日志到文件吗，只是打印到屏幕吗

**Comment by Womsxd** [comment]
只是打印，单用户的话会推送比较完整日志，多用户的话只会推送那些账号执行失败和没执行
