### ISSUE TITLE
可否增加一个树脂检测和冒险时长？

### ISSUE THREAD

**Issue by holll** [Womsxd/AutoMihoyoBBS#81]

**Comment by kmzs123** [comment]
其实更推荐用已经做好的树脂脚本，毕竟这个仓库是签到为主，重复时间一般为一天一次，树脂一天一次也没什么作用。
另外，已经做好的树脂脚本还挺多的了

**Comment by holll** [comment]
> 其实更推荐用已经做好的树脂脚本，毕竟这个仓库是签到为主，重复时间一般为一天一次，树脂一天一次也没什么作用。 另外，已经做好的树脂脚本还挺多的了

其实因为其他的脚本比较复杂，说明书不详细，就这个最好用
