### ISSUE TITLE
部分时候未能完全完成任务

### ISSUE THREAD

**Issue by nyano** [Womsxd/AutoMihoyoBBS#82]
110米游币任务，部分时候只完成90，还有20未完成。
经查验，为浏览帖子20未完成
`正在看帖......

https://bbs-api.mihoyo.com:443 "GET /post/api/getPostFull?post_id=20761692 HTTP/1.1" 200 1024

看帖：没抽到凌华的过来集合 成功

https://bbs-api.mihoyo.com:443 "GET /post/api/getPostFull?post_id=20761863 HTTP/1.1" 200 55

https://bbs-api.mihoyo.com:443 "GET /post/api/getPostFull?post_id=20606079 HTTP/1.1" 200 None

看帖：开服玩家几乎所有体力都打圣遗物练度能有多少（主c篇） 成功`

`正在获取任务列表

https://bbs-api.mihoyo.com:443 "GET /apihub/sapi/getUserMissionsState HTTP/1.1" 200 754

似乎还有任务没完成，今天还能获得20

今天已经获得90个米游币，还能获得20个米游币，目前有14080个米游币`
上述有个200通过，但未能获取到结果

请求增加个未达到获取上线，重复再运行的功能

另外，推送是否能增加个，全部完成不推送，有错误或未完成再推送？
谢谢

**Comment by djxyy5505** [comment]
一般来说，连续签到5天以上才能每天110米游币。你可以看看米游社的任务，还有啥是没运行的

**Comment by nyano** [comment]
是连续的.就是十几天才有一次这种情况.重复有2-3次.都是看帖,然后我就手动登米游社开个就+20了

**Comment by Womsxd** [comment]
已添加重试
