### ISSUE TITLE
米游社的签到错误，错误代码如下，实在看不出来

### ISSUE THREAD

**Issue by gtxy22** [Womsxd/AutoMihoyoBBS#83]
START RequestId: 6a1d4300-e5c6-4f09-80a5-c87594e54e34

Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None, status=None)

Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None, status=None)

Init Report RequestId: 6a1d4300-e5c6-4f09-80a5-c87594e54e34 Coldstart: 701ms (PullCode: 96ms InitRuntime: 6ms InitFunction: 599ms) Memory: 128MB MemUsage: 16.58MB

Config加载完毕

Starting new HTTPS connection (1): webapi.account.mihoyo.com:443

https://webapi.account.mihoyo.com:443 "GET /Api/cookie_accountinfo_by_loginticket?login_ticket=K5ibDiSNiaqiBZViV8g64qg5NxzHdtQfozDZ9epz HTTP/1.1" 200 578

Starting new HTTPS connection (1): api-takumi.mihoyo.com:443

https://api-takumi.mihoyo.com:443 "GET /auth/api/getMultiTokenByLoginTicket?login_ticket=K5ibDiSNiaqiBZViV8g64qg5NxzHdtQfozDZ9epz&token_types=3&uid=157593358 HTTP/1.1" 200 184

登录成功！

正在保存Config！

ERROR RequestId: 6a1d4300-e5c6-4f09-80a5-c87594e54e34 Result: Traceback (most recent call last):   File "/var/user/index.py", line 9, in main_handler     status_code, push_message = main.main()   File "/var/user/main.py", line 23, in main     login.login()   File "/var/user/login.py", line 28, in login     config.save_config()   File "/var/user/config.py", line 75, in save_config     with open(config_Path, "r+") as f: OSError: [Errno 30] Read-only file system: '/var/user/config/config.json'

END RequestId: 6a1d4300-e5c6-4f09-80a5-c87594e54e34

Report RequestId: 6a1d4300-e5c6-4f09-80a5-c87594e54e34 Duration: 405ms Memory: 128MB MemUsage: 17.74MB

**Comment by gtxy22** [comment]
![image](https://user-images.githubusercontent.com/59104199/164149631-ceb1f761-bb14-405b-9a40-845aed3e409c.png)
windows运行的图片，但文件好像没变化

**Comment by Womsxd** [comment]
单用户本地运行 main.py

**Comment by gtxy22** [comment]
![image](https://user-images.githubusercontent.com/59104199/164149912-14cfbebd-dfec-4509-8d27-4f92acd3e3fc.png)
这是单用户的图片，cookie复制的是字符串，config文件夹下的文件和config.py都设置了cookie

**Comment by Womsxd** [comment]
？？？？config.py不用设置啊
云函数那边还是无法写入文件，到本地连文件都不会执行了是什么情况？？？？？

**Comment by gtxy22** [comment]
![image](https://user-images.githubusercontent.com/59104199/164150727-153e82c2-6bf2-4b26-a404-4b94e5088416.png)
![image](https://user-images.githubusercontent.com/59104199/164150730-e53d0461-60e6-4098-b7a7-0cd410c10ccc.png)
在powershell 里面也是不执行
![image](https://user-images.githubusercontent.com/59104199/164150829-dbfb47c1-f9e7-4add-abbb-9f7924ac4b83.png)
python的版本3.10，可能是安装python过程的问题吗？

**Comment by Womsxd** [comment]
不可能啊，只要动config.json就行了

**Comment by gtxy22** [comment]
是要安装什么依赖吗?

**Comment by Womsxd** [comment]
依赖是只要httpx或者requests二选一就行了，而且这两依赖不安装是必定报错的

**Comment by gtxy22** [comment]
![image](https://user-images.githubusercontent.com/59104199/164153719-2a8f47bb-5956-4ba7-a9d9-20537c375c89.png)
安装完requests之后在vscode可以运行，在powershell和cmd依然不行
上图是vs code 运行过后的报错

**Comment by Womsxd** [comment]
这个。。。请你先关掉这个终端。。
还有我现在不知道脚本是什么情况下退出的

**Comment by gtxy22** [comment]
![image](https://user-images.githubusercontent.com/59104199/164155202-1947a9ae-6bc2-4cb6-8c87-48d2e6387b59.png)
刚才可能是没有设置环境路径，上图是用终端运行的报错

**Comment by Womsxd** [comment]
@gtxy22 
ticket泄露了~不过问题不大
还有现在的报错是网络问题，推荐你查一下报错吧
