### ISSUE TITLE
可以考虑下对多游戏账户的选择签到

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#86]
作者，您好。像我一个米游社账号绑定了多个崩坏3的游戏账号，可以在配置文件中选择签到哪些账号。我没这样的需求，不过作者你空闲了可以考虑增加这个功能。(*￣︶￣)

**Comment by Womsxd** [comment]
要加的话简单，我之后更新的时候稍微带一下吧

**Comment by Womsxd** [comment]
你是希望黑名单为主还是白名单为主？我是会更偏向于黑名单

**Comment by Teconheci** [comment]
都行吧。不过我也倾向于黑名单

**Comment by Womsxd** [comment]
> 都行吧。不过我也倾向于黑名单

确实，不过黑白都好写（也就是in和not in的区别

**Comment by Womsxd** [comment]
问个问题，你感觉在黑名单里的需要log输出和推送里面提示吗？

**Comment by Womsxd** [comment]
已经开始写config v5版本里的一些功能了

**Comment by Teconheci** [comment]
> 问个问题，你感觉在黑名单里的需要log输出和推送里面提示吗？

不用吧

**Comment by Teconheci** [comment]
大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码

**Comment by Teconheci** [comment]
对connect进行各种decode解码也是各种乱码

**Comment by Teconheci** [comment]
对connect进行各种decode解码也是各种乱码我傻了，请求但我时候加了压缩

**Comment by Teconheci** [comment]
> 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码

没事了，我傻了，请求的时候加了压缩

**Comment by Womsxd** [comment]
> > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> 
> 没事了，我傻了，请求的时候加了压缩

gzip还是br？gzip我记得httpx会自动解压

**Comment by Teconheci** [comment]
> > > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> > 
> > 没事了，我傻了，请求的时候加了压缩
> 
> gzip还是br？gzip我记得httpx会自动解压

br，我直接把br去了，先不导第三方包了

**Comment by Teconheci** [comment]
> > > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> > 
> > 没事了，我傻了，请求的时候加了压缩
> 
> gzip还是br？gzip我记得httpx会自动解压

对了，游戏月卡这些能抓包然后访问获得吗。每日任务的话，我试了下fiddle，fiddle没显示请求

**Comment by Teconheci** [comment]
> > > > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> > > 
> > > 没事了，我傻了，请求的时候加了压缩
> > 
> > gzip还是br？gzip我记得httpx会自动解压
> 
> 对了，游戏月卡这些能抓包然后访问获得吗。每日任务的话，我试了下fiddle，fiddle没显示请求

忘了，fiddle只能抓网络层的，等会用wireshark试试

**Comment by Womsxd** [comment]
> > > > > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> > > > 
> > > > 没事了，我傻了，请求的时候加了压缩
> > > 
> > > gzip还是br？gzip我记得httpx会自动解压
> > 
> > 对了，游戏月卡这些能抓包然后访问获得吗。每日任务的话，我试了下fiddle，fiddle没显示请求
> 
> 忘了，fiddle只能抓http，等会用wireshark试试

游戏内的话是kcp，你要处理游戏内数据的话不大可能，我这边目前用的接口全是http接口

**Comment by Teconheci** [comment]
> > > > > > 大佬，我想问下，我用httpx访问接口后，获得的html文件的响应怎么编解码，抓包工具上都是正常显示的，Python里无论咋整，打印出来都是乱码，响应头显示的是gbk编码
> > > > > 
> > > > > 没事了，我傻了，请求的时候加了压缩
> > > > 
> > > > gzip还是br？gzip我记得httpx会自动解压
> > > 
> > > 对了，游戏月卡这些能抓包然后访问获得吗。每日任务的话，我试了下fiddle，fiddle没显示请求
> > 
> > 忘了，fiddle只能抓http，等会用wireshark试试
> 
> 游戏内的话是kcp，你要处理游戏内数据的话不大可能，我这边目前用的接口全是http接口

好吧，配置文件里game中的auto_checkin有啥用，我看没对进行判断啊，只是有个赋值为false的操作
