### ISSUE TITLE
readme的云函数的步骤5应该修改下

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#88]
原来的：执行方法填写 index.main_handler,多用户请填写**main_handler_mulit**
应修改为：执行方法填写 index.main_handler,多用户请填写**index.main_handler_mulit**

**Comment by Teconheci** [comment]
大佬，cookie大概多久失效一次

**Comment by Womsxd** [comment]
> 大佬，cookie大概多久失效一次

bzd，我自己是快半年了还能用

**Comment by Womsxd** [comment]
已更改

**Comment by Teconheci** [comment]
> 

OKOK

**Comment by Teconheci** [comment]
> 已更改

okok
