### ISSUE TITLE
 获取原神账号列表失败的问题

### ISSUE THREAD

**Issue by Kirrito-k423** [Womsxd/AutoMihoyoBBS#89]
`2022-04-24T10:22:36 INFO 正在进行原神签到`
`2022-04-24T10:22:36 INFO 正在获取米哈游账号绑定的原神账号列表...`
`2022-04-24T10:22:36 WARNING 获取原神账号列表失败！`

小白来问问怎么回事~

前天还没问题，米游币签到没问题

**Comment by Kirrito-k423** [comment]
emmm, 更新cookie就好了

**Comment by Womsxd** [comment]
这里要不我加个提示？
