### ISSUE TITLE
请问可以增加一个每天定时自动签到的功能吗

### ISSUE THREAD

**Issue by jx9468** [Womsxd/AutoMihoyoBBS#9]
文件挂在服务器上，每天要登入运行有点小麻烦，希望大佬能增加一个定时自动签到的功能😊

**Comment by Womsxd** [comment]
Windows可以用计划任务程序

**Comment by jx9468** [comment]
> 用

请问触发器后的操作怎么填，“D:\桌面\AutoMihoyoBBS-master python main.py”这样吗？

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/131485827-311df3fb-8976-4b63-9069-c35560594cf7.png)
第一项填写Python路径
第二项填写脚本
第三项填写脚本位置

**Comment by Womsxd** [comment]
> > 用
> 
> 请问触发器后的操作怎么填，“D:\桌面\AutoMihoyoBBS-master python main.py”这样吗？

在你这边
第二项是main.py
第三项是D:\桌面\AutoMihoyoBBS-master

脚本建议每日执行(防止出现问题)2-3次

**Comment by jx9468** [comment]
> > > 用
> > 
> > 
> > 请问触发器后的操作怎么填，“D:\桌面\AutoMihoyoBBS-master python main.py”这样吗？
> 
> 在你这边
> 第二项是main.py
> 第三项是D:\桌面\AutoMihoyoBBS-master
> 
> 脚本建议每日执行(防止出现问题)2-3次

OK了，多谢大佬。
