### ISSUE TITLE
新版本配置文件建议收集

### ISSUE THREAD

**Issue by Womsxd** [Womsxd/AutoMihoyoBBS#90]
脚本预计在4月30号更新v5版本的json格式的配置文件，预计在5月底(或6月底)正式停用v4版本配置文件的支持，期间云函数用户会在v5版本正式上线后通过每日执行的后的推送服务来进行通知，其他能写文件的用户会尝试**自动更新**到v5版本。

**现在征集v5版本的配置的相关建议**

v5版本的config文件要求是以小写为主

当前v5版本的配置文件（2022-4-25版本）：

```json
{
  "enable": false,
  "version": 5,
  "account": {
    "cookie": "",
    "login_ticket": "",
    "stuid": "",
    "stoken": ""
  },
  "mihoyobbs": {
    "enable": true,
    "checkin": true,
    "checkin_multi": true,
    "checkin_multi_list": [2, 5],
    "read_posts": true,
    "like_posts": true,
    "un_like": true,
    "share_post": true
  },
  "games": {
    "cn": {
      "enable": true,
      "hokai2": {
        "auto_checkin": false,
        "black_list": []
      },
      "honkai3rd": {
        "auto_checkin": false,
        "black_list": []
      },
      "tears_of_themis": {
        "auto_checkin": false,
        "black_list": []
      },
      "genshin": {
        "auto_checkin": false,
        "black_list": []
      }
    },
    "os": {
      "enable": false,
      "cookie": "",
      "genshin": {
        "auto_checkin": false,
        "black_list": []
      }
    }
  }
}
```

**Comment by Womsxd** [comment]
原神国际服的兼容目前属于占坑位状态，目前优先支持崩坏2，其次为原神国际服

**Comment by kmzs123** [comment]
现在未定也有签到了，预计铁道也会有

**Comment by Teconheci** [comment]
pushdeer目前已经支持了吗，没用过这个，咋配置呀

**Comment by Teconheci** [comment]
推送配置文件可以改下，感觉有点乱，push_server选择好推送方式后，下面的push_token的存在有些懵

**Comment by Womsxd** [comment]
> 现在未定也有签到了，预计铁道也会有

???草， 不过问题也不大，可以写一下自动签到

**Comment by Womsxd** [comment]
目前是希望config版本出现改动后，内容未来不会出现一些重大改动，这个v4–>v5是打算抛弃一堆历史包裹，解决这个项目一开始给自己用的计划，同时也方便拓展未来需要的功能

**Comment by Womsxd** [comment]
现在这里还要征集一下未定事件簿的名称，是使用官方翻译的Tears of Themis还是其他的名称

**Comment by Womsxd** [comment]
> 现在未定也有签到了，预计铁道也会有

未定已加入预备了，先把坑位占好了

**Comment by BiuXiaoXiong** [comment]
2022-04-30T17:20:47 INFO Config加载完毕
2022-04-30T17:20:47 WARNING Config未启用！

运行后的提示  因为我配置的不对吗

**Comment by Teconheci** [comment]
云服务器的用户不能自动更新吗？那是不是本地跑一遍再上传

**Comment by Teconheci** [comment]
作者，我改配置文件的时候突然觉得黑白名单都有好些

**Comment by Womsxd** [comment]
> 云服务器的用户不能自动更新吗？那是不是本地跑一遍再上传

云函数在函数执行的时候无法进行文件写操作，所以需要本地跑一边重新上传，当然也可以不用本地重新跑一边，在云函数控制台进脚本目录后python36 main.py or python36 main_multi.py autorun跑就行了，当然好像也可以git clone和git pull(

**Comment by Teconheci** [comment]
黑名单判断那里有问题了，我试的崩3的，continue后，仍然会执行下面的签到，只是if下的语句不会执行，蛮奇怪的

**Comment by GardeniaFlower** [comment]
唯一的请求：config里边加注释😂

**Comment by Womsxd** [comment]
> 唯一的请求：config里边加注释😂

json里面不好加，可能之后再次塞readme里面吧

**Comment by jjjyyyllll** [comment]
"genshin": {
        "auto_checkin": false,
        "black_list": []

设置为true 原神也不签到了啊 提示
2022-05-05T13:24:13 WARNING 获取账号签到信息失败！
2022-05-05T13:24:13 INFO Config保存完毕
2022-05-05T13:24:13 ERROR 账号Cookie有问题！
2022-05-05T13:24:13 INFO 正在执行推送......
2022-05-05T13:24:13 INFO 推送完毕......
{"data":null,"message":"尚未登录","retcode":-100}
