### ISSUE TITLE
推送消息文本的改进意见

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#91]
我使用的是pushdeer
目前的push_message的首句是：[米游社脚本]执行成功！
可以考虑把首句改进：如果全部执行成功，应推送  [米游社脚本]全部执行成功！
因为只在锁屏界面上看到的通知只有首句
下面是代码部分的意见(没看完不确定流程看懂没)：
我粗看了下代码，多用户主函数里push函数的状态参数默认是0
可以考虑全部成功，部分失败和全部失败三种状态

还有配置文件里的push_token是不是可以删除

**Comment by Womsxd** [comment]
> 我使用的是pushdeer 目前的push_message的首句是：[米游社脚本]执行成功！ 可以考虑把首句改进：如果全部执行成功，应推送 [米游社脚本]全部执行成功！ 因为只在锁屏界面上看到的通知只有首句 下面是代码部分的意见(没看完不确定流程看懂没)： 我粗看了下代码，多用户主函数里push函数的状态参数默认是0 可以考虑全部成功，部分失败和全部失败三种状态
> 
> 还有配置文件里的push_token是不是可以删除

部分失败需不需要把已停用的脚本也考虑进去？

**Comment by Womsxd** [comment]
pushdeer的用的是[pushdeer]那边的token
pushtoken是给server酱和pushplus的用户使用的，如果pushdeer不支持自定义服务器的话估计也会扔到那边处理

**Comment by Womsxd** [comment]
```ini
[setting]
enable=false
push_server=pushdeer

[pushdeer]
api_url=https://api2.pushdeer.com
token=
```

这是pushdeer的最精简版本

**Comment by Teconheci** [comment]
> > 我使用的是pushdeer 目前的push_message的首句是：[米游社脚本]执行成功！ 可以考虑把首句改进：如果全部执行成功，应推送 [米游社脚本]全部执行成功！ 因为只在锁屏界面上看到的通知只有首句 下面是代码部分的意见(没看完不确定流程看懂没)： 我粗看了下代码，多用户主函数里push函数的状态参数默认是0 可以考虑全部成功，部分失败和全部失败三种状态
> > 还有配置文件里的push_token是不是可以删除
> 
> 部分失败需不需要把已停用的配置文件也考虑进去？

这样的话，我觉得可以加一个用户对这个配置文件想不想要使用的字段enable_Config_expect。状态改为两个就可以了，执行成功数与该字段为true的数目相同就显示全部执行成功，不同就显示执行出现问题

**Comment by Teconheci** [comment]
> pushdeer的用的是[pushdeer]那边的token pushtoken是给server酱和pushplus的用户使用的，如果pushdeer不支持自定义服务器的话估计也会扔到那边处理

明白了

**Comment by Womsxd** [comment]
要不改为4种情况？
全部执行正常
部分执行正常
部分未执行
全部执行失败

**Comment by Teconheci** [comment]
> 要不改为4种情况？
> 全部执行正常
> 部分执行正常
> 部分未执行
> 全部执行失败
> 推送相关的更新的话今天就可以进行更新了，也无需动配置文件

也可以。我提出加个字段是因为可能有的人就是想要一些配置文件不执行，跟代码改成不执行区分开

**Comment by Womsxd** [comment]
> > 要不改为4种情况？
> > 全部执行正常
> > 部分执行正常
> > 部分未执行
> > 全部执行失败
> > 推送相关的更新的话今天就可以进行更新了，也无需动配置文件
> 
> 也可以。我提出加个字段是因为可能有的人就是想要一些配置文件不执行，跟代码改成不执行区分开

字段感觉可以不用加，失败之后不是会清空cookie么，我在清空cookie后写CookieError进去然后进行判断就行了

**Comment by Teconheci** [comment]
> > > 要不改为4种情况？
> > > 全部执行正常
> > > 部分执行正常
> > > 部分未执行
> > > 全部执行失败
> > > 推送相关的更新的话今天就可以进行更新了，也无需动配置文件
> > 
> > 也可以。我提出加个字段是因为可能有的人就是想要一些配置文件不执行，跟代码改成不执行区分开
> 
> 字段感觉可以不用加，失败之后不是会清空cookie么，我在清空cookie后写CookieError进去然后进行判断就行了

这样的话部分未执行的情况我觉得就不用了，部分未执行标题就不用体现了

**Comment by Womsxd** [comment]
那这些因为cookie出错导致未执行的就塞到失败里面好了？

**Comment by Teconheci** [comment]
> 那这些因为cookie出错导致未执行的就塞到失败里面好了？

是噻，具体原因要去看日志嘛

**Comment by Womsxd** [comment]
已经更新~

**Comment by Womsxd** [comment]
具体实现的话就是当cookie的值为CookieError的时候直接抛出一个异常，然后多用户这里是会捕获这个异常并加入error列表里面

**Comment by Teconheci** [comment]
> 具体实现的话就是当cookie的值为CookieError的时候直接抛出一个异常，然后多用户这里是会捕获这个异常并加入error列表里面

欧克欧克，我重新部署下。

**Comment by Womsxd** [comment]
```python
if status == 0:
        return "「米游社脚本」执行成功!"
    elif status == 1:
        return "「米游社脚本」执行失败!"
    elif status == 2:
        return "「米游社脚本」部分账号执行失败！"
```

这是目前的3个推送标题

**Comment by Teconheci** [comment]
有些小问题
main_multi.py第61行，应该加个结果错误数不等于0的判断条件
elif `len(results["error"]) != 0 and` len(results["error"]) < len(config_list):

**Comment by Womsxd** [comment]
> 有些小问题
> main_multi.py第61行，应该加个结果错误数不等于0的判断条件
> elif `len(results["error"]) != 0 and` len(results["error"]) < len(config_list):

修了，刚自己也跑过了，正常，只要error != 0就行了，全寄的情况就是等于config的总数
