### ISSUE TITLE
本地执行成功，但是阿里云测试失败

### ISSUE THREAD

**Issue by h5nc** [Womsxd/AutoMihoyoBBS#92]
非常感谢提供这个工具！

我在本地配置成功也测试过签到，但是在阿里云执行是出现这个问题

[ERROR] Request failed: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a8bb80898>: Failed to establish a new connection: [Errno 110] Connection timed out',))

看起来像是阿里云不能访问外网？
请问这个怎么解决呢？

一直用的腾讯云，没什么问题，但是腾讯云即将没有免费的了，希望能有替代产品。

其实阿里云我也不确定是完全免费，看到“全球外网流量”的部分没有免费额度，却已经有了流量，不知道是不是会秋后算账。。
如果有完全免费（额度内）的云服务推荐还希望介绍一下。。谢谢

**Comment by Womsxd** [comment]
[阿里云云函数计费说明](https://help.aliyun.com/document_detail/54301.html)
公网入流量不计费。例如，通过函数向公网发起网络请求时，收到响应（Response）时所产生的流量，以及通过公网调用函数，客户端发起网络请求（Request）时所产生的流量。

**Comment by Womsxd** [comment]
可以考虑整个公网出流量包？
10 GB/年：5.00元
[价格界面](https://help.aliyun.com/document_detail/263324.html)

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/165019050-b082b82f-d2a7-4237-b150-2bfeb8b0dc07.png)
![image](https://user-images.githubusercontent.com/45663319/165019110-ac106c21-004f-43b0-9ca0-a3b2f06aedd0.png)

**Comment by Womsxd** [comment]
腾讯云有1块钱一个月的套餐包，一年差不多12元，阿里云云函数访问网站的流量应该是归属于**函数内数据传输流量**，按照一个月1g既0.8元计算，一年9.6，感觉买套餐包会划算点？

**Comment by Womsxd** [comment]
国内免费的话还有aws（亚马逊云国区）宁夏区域，有免费的调用，似乎是不会计费流量

**Comment by h5nc** [comment]
十分感谢！设置了访问公网后一切正常了orz
看来阿里还是要收费的。。现在看账单还是0元，我也没有设置支付选项，看看月底是什么情况吧。亚马逊试验一下

**Comment by Womsxd** [comment]
> 十分感谢！设置了访问公网后一切正常了orz 看来阿里还是要收费的。。现在看账单还是0元，我也没有设置支付选项，看看月底是什么情况吧。亚马逊试验一下

看阿里云的计费了，如果是可以能完全白嫖或者5块钱购买一年的流量都感觉还行？

**Comment by h5nc** [comment]
估计蚊子腿也就这些钱哈哈，总之这个issue的问题解决了，谢谢谢谢！

**Comment by Teconheci** [comment]
> 非常感谢提供这个工具！
> 
> 我在本地配置成功也测试过签到，但是在阿里云执行是出现这个问题
> 
> [ERROR] Request failed: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a8bb80898>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> 
> 看起来像是阿里云不能访问外网？ 请问这个怎么解决呢？
> 
> 一直用的腾讯云，没什么问题，但是腾讯云即将没有免费的了，希望能有替代产品。
> 
> 其实阿里云我也不确定是完全免费，看到“全球外网流量”的部分没有免费额度，却已经有了流量，不知道是不是会秋后算账。。 如果有完全免费（额度内）的云服务推荐还希望介绍一下。。谢谢

腾讯云 云函数即将不免费了？没看到有公告啊

**Comment by h5nc** [comment]
我收到了短信提醒免费制度升级，本以为是升级，结果说的是以后免费套餐前三个月免费，之后收费，具体内容大概是这篇文章的内容
https://www.landian.vip/archives/93603.html

**Comment by Womsxd** [comment]
> > 非常感谢提供这个工具！
> > 我在本地配置成功也测试过签到，但是在阿里云执行是出现这个问题
> > [ERROR] Request failed: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a8bb80898>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> > 看起来像是阿里云不能访问外网？ 请问这个怎么解决呢？
> > 一直用的腾讯云，没什么问题，但是腾讯云即将没有免费的了，希望能有替代产品。
> > 其实阿里云我也不确定是完全免费，看到“全球外网流量”的部分没有免费额度，却已经有了流量，不知道是不是会秋后算账。。 如果有完全免费（额度内）的云服务推荐还希望介绍一下。。谢谢
> 
> 腾讯云 云函数即将不免费了？没看到有公告啊

短信我也收到了

**Comment by h5nc** [comment]
我现在把项目移动到了aws日本节点，看样子好像是免费的

**Comment by Womsxd** [comment]
aws不是有国内的节点吗，亚马逊中国（

**Comment by Womsxd** [comment]
我打算到5月15号，停掉云函数上面的全部脚本，然后迁移到自己的学生机上面

**Comment by Teconheci** [comment]
> 我收到了短信提醒免费制度升级，本以为是升级，结果说的是以后免费套餐前三个月免费，之后收费，具体内容大概是这篇文章的内容 https://www.landian.vip/archives/93603.html

我打电话问了，客服说没有，虽然她也是看的公告。是你收到的短信上明确说了第四个月后就没有免费额度了吗

**Comment by Teconheci** [comment]
> 【腾讯云】尊敬的腾讯云用户，您好！ 2022 年 5 月 23 日开始，免费额度将进行升级：前三个月免费额度将升级为享受0元购买云函数个人高级版套餐包限时特惠折扣，第四个月开始可根据业务需要选购，优惠低至3.4折。若没有及时购买将面临停服风险。登录腾讯云账号（账号 ID：xxxx，昵称：xxxx），套餐包购买链接： https://mc.tencent.com/b9BkWjPD 。

又问了一次，要停的话会出公告的

**Comment by Womsxd** [comment]
现在是真的等5.23开始了，腾讯这公告真的发起来令人恐慌

**Comment by Teconheci** [comment]
> 现在是真的等5.23开始了，腾讯这公告真的发起来令人恐慌

先不转了，发了公告再说，实在没有就付点钱

**Comment by h5nc** [comment]
> aws不是有国内的节点吗，亚马逊中国（

我人在日本，不知道国内的免费是怎样才能办。
日本站好像不需要学生，就开开试试了

**Comment by Womsxd** [comment]
> > aws不是有国内的节点吗，亚马逊中国（
> 
> 我人在日本，不知道国内的免费是怎样才能办。
> 日本站好像不需要学生，就开开试试了

人在日本好像问题不大，还以为是在国内(
