### ISSUE TITLE
腾讯云pushplus推送问题

### ISSUE THREAD

**Issue by nyano** [Womsxd/AutoMihoyoBBS#93]
首先脚本没问题，本地测试通过，我来问问有木有跟我一样问题的
问题主要发生在近期更新，即我提出需要重试功能后
【config.json】和【push.ini】使用原始可用版本，并没有修改

执行日志反馈正常：
推送所用的服务为：pushplus

Starting new HTTPS connection (1): www.pushplus.plus:443

https://www.pushplus.plus:443 "POST /send HTTP/1.1" 200 None

推送完毕......

但推送完毕，实际没有推送，pushplus的推送测试正常

经多次测试后发现：
1.pushdeer等其他推送正常，就pushplus不正常
2.脚本运行在大陆地区服务器【广东】【上海】均无提示，国外区域正常推送，怀疑把pushplus封了？但是更新前我推送正常的
3.pushplus自身有问题，如图
![QQ截图20220427091430](https://user-images.githubusercontent.com/5079651/165418829-03b50cf6-a44d-431f-b7ce-e6c73e00969a.png)

【账户推广变动提醒】【IT服务单受理通知】【未读语音消息提醒】【告警通知】都是什么鬼

在pushplus后台找历史消息，并不存在测试的推送信息，意味着pushplus并未收到推送

**Comment by nyano** [comment]
另外推送通知发现【已连续签到X天】中，天数不含当天。即今天27号但是显示已连续签到26天。已验证米游社中为27天。

**Comment by Womsxd** [comment]
在企业微信测试支持的时候对pushplus有过改动，主要改动为http变成https
79d631f25e810a1402666a3f36307a30f546c1c7

**Comment by nyano** [comment]
> 在企业微信测试支持的时候对pushplus有过改动，主要改动为http变成https [79d631f](https://github.com/Womsxd/AutoMihoyoBBS/commit/79d631f25e810a1402666a3f36307a30f546c1c7)

确实，之前的日志

推送所用的服务为：pushplus

Starting new HTTP connection (1): www.pushplus.plus:80

http://www.pushplus.plus:80 "POST /send HTTP/1.1" 200 88
正常。
后面日志为：200 None

问题是 我把地点转为 国外或本机运行都正常，仅在如上海、广东等服务器中运行 通知推送失败
不清楚哪里的问题

**Comment by nyano** [comment]
测试 手动改为http模式就正常了。

**Comment by Womsxd** [comment]
我现在也搞不清楚问题出现在什么地方，我这边获取到pushplus的ip也是国内阿里云的

**Comment by Womsxd** [comment]
好像找到问题了，pushplus有两个域名好像
pushplus.plus和pushplus.hxtrip.com，试试改成https://pushplus.hxtrip.com/
？

**Comment by Womsxd** [comment]
如果改成https://pushplus.hxtrip.com/ 能正常推送的话我就会修改成国内搜到的这个地址，.plus是我拿google搜到的

**Comment by nyano** [comment]
测试无效，而且这个好像是假pushplus，好像是绑的另外一个小程序。
完全找不到原因。关键是外域 和我本机测试都是正常的，说明代码段上也是没问题的，即使我手动直接浏览器输GET地址都能成功，pushplus能接收到。但是在上海和广东服务器就是不成功。改为http则可用。
pushplus好像也没问题，http://www.pushplus.plus/doc/help/https.html

=》收得到
http://www.pushplus.plus:80 "POST /send HTTP/1.1" 200 None

=》收不到
https://www.pushplus.plus:443 "POST /send HTTP/1.1" 200 None

日志反馈也是正常的，但是就是收不到，太奇怪

**Comment by Womsxd** [comment]
现在是希望我降级到http还是之后提供一个开关？

**Comment by nyano** [comment]
并不知道是我个人问题还是共性问题。手动改一改并不是什么难事，我认为并不需要动，毕竟只在2个服务器上有问题，确定是https问题的话 说不定是服务器端SSL有问题也说不定 没必要改动
