### ISSUE TITLE
本地执行似乎无法写入json文件

### ISSUE THREAD

**Issue by LuZhuanz** [Womsxd/AutoMihoyoBBS#94]
<img width="737" alt="屏幕截图 2022-04-28 190401" src="https://user-images.githubusercontent.com/92381197/165738721-24bfcc60-bd51-445d-9394-e7c3834ecfef.png">

**Comment by Womsxd** [comment]
新用户草，你去使用v5版本的配置文件吧

**Comment by Womsxd** [comment]
草？今晚估计要提前上v5版本了，等我修一下吧

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/archive/e9749386f5d549353f486b265fd396bae426a6e6.zip
先下载这个版本吧

**Comment by Womsxd** [comment]
今晚估计没空修了

**Comment by Womsxd** [comment]
bug fix
