### ISSUE TITLE
v5版本运行报错

### ISSUE THREAD

**Issue by forchannot** [Womsxd/AutoMihoyoBBS#95]
![image](https://user-images.githubusercontent.com/100580891/166090114-3518956e-6bc7-4eb5-aa27-2c6772795551.png)

**Comment by forchannot** [comment]
> ![image](https://user-images.githubusercontent.com/100580891/166090114-3518956e-6bc7-4eb5-aa27-2c6772795551.png)

![image](https://user-images.githubusercontent.com/100580891/166090833-54b26570-dbcb-48c5-af1b-5c05cd287f25.png)
ton同样的cookie，这是v4没问题

**Comment by Womsxd** [comment]
修复了，是疏忽导致的（

**Comment by forchannot** [comment]
> 修复了，是疏忽导致的（

好的，顺便再问一个问题，我是用浏览器无痕模式抓的cookie，但是为啥每天都会失效呢

**Comment by Womsxd** [comment]
天天失效？
是社区无法签到还是原神无法签到

**Comment by forchannot** [comment]
> 天天失效？ 是社区无法签到还是原神无法签到

就都无法，直接说cookie已失效

**Comment by Womsxd** [comment]
那估计是米游社那边炸了，这种情况我现在也不清楚是什么回事，我自己是已经撑过快9个月了，基本上是没遇到过这种情况

**Comment by forchannot** [comment]
> 那估计是米游社那边炸了，这种情况我现在也不清楚是什么回事，我自己是已经撑过快9个月了，基本上是没遇到过这种情况

但我在我的机器人那里绑定的cookie没失效，仍然能够获取角色配队深渊札记等信息，这些都是需要cookie的，而且机器人那边的手动签到没问题，但是机器人不能做米游币任务，但说明cookie应该没失效吧

**Comment by Womsxd** [comment]
没有，这就是米游币那边的cookie炸了

**Comment by Teconheci** [comment]
> 没有，这就是米游币那边的cookie炸了

游戏账号黑名单咋配置啊

**Comment by Womsxd** [comment]
> > 没有，这就是米游币那边的cookie炸了
> 
> 游戏账号黑名单咋配置啊


[1234,1245] 里面填uid，只支持int类型uid，不支持str

**Comment by Teconheci** [comment]
> > > 没有，这就是米游币那边的cookie炸了
> > 
> > 游戏账号黑名单咋配置啊
> 
> 
> [1234,1245] 里面填uid，只支持int类型uid，不支持str

欧克欧克

**Comment by Teconheci** [comment]
> > > 没有，这就是米游币那边的cookie炸了
> > 
> > 游戏账号黑名单咋配置啊
> 
> 
> [1234,1245] 里面填uid，只支持int类型uid，不支持str

试了下，支持str,不是int😂
