### ISSUE TITLE
想问一下config里边的一些意思是什么

### ISSUE THREAD

**Issue by GardeniaFlower** [Womsxd/AutoMihoyoBBS#98]
"checkin_multi_list": [
            2, 
            5
        ], 
这里是啥呀，2和5又是啥。。。
"os": {
            "enable": false, 
            "cookie": "", 
            "genshin": {
                "auto_checkin": false, 
                "black_list": []
这里的OS又是什么？

**Comment by Womsxd** [comment]
os那块指国际服，目前处于占位置，没写实际功能
"checkin_multi_list"就是老版本config文件里的"bbs_Signin_multi_list"，可以在readme里面查看到详细的说明

**Comment by GardeniaFlower** [comment]
我有的账号想

> os那块指国际服，目前处于占位置，没写实际功能 "checkin_multi_list"就是老版本config文件里的"bbs_Signin_multi_list"，可以在readme里面查看到详细的说明

我有俩账号想只签到崩坏2的每日福利，但是不知道该改哪个去关原神的签到福利，请问应该修改哪个地方？感谢大佬

**Comment by Womsxd** [comment]
"games": {
    "cn": {
      "enable": true,
      "hokai2": {
        "auto_checkin": true,
        "black_list": []
      },
      "honkai3rd": {
        "auto_checkin": false,
        "black_list": []
      },
      "tears_of_themis": {
        "auto_checkin": false,
        "black_list": []
      },
      "genshin": {
        "auto_checkin": false,
        "black_list": []
      }
    },

**Comment by Womsxd** [comment]
参考

**Comment by GardeniaFlower** [comment]
我就是这样设置的，它还是会提示我一下请先自己签到一次。
2022-05-01T22:20:30 WARNING 旅行者攒水ing是第一次绑定米游社，请先手动签到一次
攒水ing是我崩坏2的游戏名。。。。

**Comment by Womsxd** [comment]
> 我就是这样设置的，它还是会提示我一下请先自己签到一次。 2022-05-01T22:20:30 WARNING 旅行者攒水ing是第一次绑定米游社，请先手动签到一次 攒水ing是我崩坏2的游戏名。。。。

没签到过吗？

**Comment by Womsxd** [comment]
我崩坏2的签到点是直接照搬原神的签到代码的(发现可以通用)

**Comment by Womsxd** [comment]
```python
if not is_data["is_sub"]:  # 这个字段不知道干啥的，就先塞这里了
    log.warning(f"旅行者{i[0]}是第一次绑定米游社，请先手动签到一次")
```

**Comment by GardeniaFlower** [comment]
哦哦，原来旅行者是这个，不过我崩坏2的号签到过了呀，我2个号都自己签到过2次，但是我有个号今天特意没去签到，它提示我自己签到一次

**Comment by Womsxd** [comment]
已推送更新，屏蔽掉这个字段了，如果方便的话请在honkai2.py的第56行加一段print(is_data)然后把输出结果发我即可

**Comment by GardeniaFlower** [comment]
话说大佬应该咋更新啊😂

**Comment by Womsxd** [comment]
有安装git还是压缩包，压缩包的话直接解压覆盖就行了

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/166150821-c8ba323a-2019-413d-85a1-ba474b09e0b9.png)
加入示例

**Comment by Womsxd** [comment]
```json
{
  "retcode": 0,
  "message": "OK",
  "data": {
    "total_sign_day": 25,
    "today": "2022-04-25",
    "is_sign": false,
    "is_sub": true,
    "region": "gf01"
  }
}
```
这个是我之前抓包到的结果

**Comment by Womsxd** [comment]
> 话说大佬应该咋更新啊😂

压缩包的话要么覆盖，要么直接把config文件夹复制到新版本的文件夹里面

**Comment by GardeniaFlower** [comment]
文件我没更新上。。我是用容器的，直接git clone https://github.com/Womsxd/AutoMihoyoBBS.git 进来的。。至于那个print(is_data)输出的是这个吗？
mihoyo-bbs_1  | {'total_sign_day': 0, 'today': '2022-05-01', 'is_sign': False, 'is_sub': False, 'region': ''}
mihoyo-bbs_1  | {'total_sign_day': 0, 'today': '2022-05-01', 'is_sign': False, 'is_sub': False, 'region': ''}

**Comment by GardeniaFlower** [comment]
我服务器再跑一次git就报fatal: destination path 'AutoMihoyoBBS' already exists and is not an empty directory.了

**Comment by GardeniaFlower** [comment]
我直接照着你文件改好了

**Comment by GardeniaFlower** [comment]
解决了，原来每月第一天得自己签到。。。不过想问一下Log怎么清除呀

**Comment by Womsxd** [comment]
> 解决了，原来每月第一天得自己签到。。。不过想问一下Log怎么清除呀

log只会输出不会保存，然后估计你这号是没签到过还是因为什么奇奇怪怪的bug导致无法自动签到，我测试的号是5.1能自动签到，感觉is_sub这个字段就是有没有进行第一次签到

**Comment by GardeniaFlower** [comment]
Traceback (most recent call last):
mihoyo-bbs_1  |   File "/var/app/./main_multi.py", line 71, in <module>
mihoyo-bbs_1  |     main_multi(autorun)
mihoyo-bbs_1  |   File "/var/app/./main_multi.py", line 43, in main_multi
mihoyo-bbs_1  |     run_code, run_message = main.main()
mihoyo-bbs_1  |   File "/var/app/main.py", line 18, in main
mihoyo-bbs_1  |     config.load_config()
mihoyo-bbs_1  |   File "/var/app/config.py", line 46, in load_config
mihoyo-bbs_1  |     data = json.load(f)
mihoyo-bbs_1  |   File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
mihoyo-bbs_1  |     return loads(fp.read(),
mihoyo-bbs_1  |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
mihoyo-bbs_1  |     return _default_decoder.decode(s)
mihoyo-bbs_1  |   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
mihoyo-bbs_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
mihoyo-bbs_1  |   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
mihoyo-bbs_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
mihoyo-bbs_1  | json.decoder.JSONDecodeError: Expecting value: line 2 column 15 (char 16)
现在报这玩意了。。。。。

**Comment by Womsxd** [comment]
json文件的第二行出现错误

**Comment by GardeniaFlower** [comment]
咋解决啊，我直接重新弄了两次

**Comment by GardeniaFlower** [comment]
两次都是这个报错

**Comment by GardeniaFlower** [comment]
解决了，用的MobaXterm连接的服务器，把文件本地编辑后上传服务器，内容经常容易出现部分换行什么的或者文本乱码，必须服务器里边直接编辑才行，如果可以的话想问下有啥SSH客户端推荐吗？

**Comment by Womsxd** [comment]
> 解决了，用的MobaXterm连接的服务器，把文件本地编辑后上传服务器，内容经常容易出现部分换行什么的或者文本乱码，必须服务器里边直接编辑才行，如果可以的话想问下有啥SSH客户端推荐吗？

我这边一般使用xshell+xftp（家庭版，非马克丁代理的），如果只要执行shell的话可以使用windows的openssh(打开终端 输入ssh 用户名@ip)
